emberjs/ember-test-helpers

- Brocfile.js
- package.json
- testem.json
- tests/index.html
We're trying to update loader js in https://github.com/ember-cli/ember-cli/pull/3054 and we noticed that ember-test-helpers were producing an incorrect AMD output.  This PR replaces the old ES6 transpiler for the one that is used by Ember CLI and produces the correct output.  I also added the sourcemap concatenator which knows how to properly concat sourcemaps.
> Update ES6 module transpiler and proper sourcemap concatenation

- lib/ember-test-helpers/test-module.js
- tests/test-module-for-component-test.js
- tests/test-module-test.js
Previously, the `setup` callback was invoked via `invokeSteps` (and
therefore was bound to the `TestModule` instance itself).  Now it is
invoked with the same context as the tests themselves.
* Ensure `setup` callback is invoked with the test context.
* Ensure `teardown` callback is invoked with the test context.
* Removed `beforeTeardown`.
* Added `afterTeardown` which is invoked with the test-module context.
* Simplify callback ordering tests.
/cc @dgeb
> Ensure that `setup` callback is invoked with the correct context.

- lib/ember-test-helpers/test-module-for-component.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-test.js
Provides access to any of a module's properties (e.g. `container`, `callbacks`, etc.) from within a callback.
Attn: @rwjblue
> Ensure callbacks are called in the test module's context.

- lib/ember-test-helpers/isolated-container.js
Prevent noisy deprecation warnings in tests until we introduce usage
of the ApplicationInstance (complete with its own container and 
registry) into ember-test-helpers.
Tested with ember 1.11 beta as well as 1.10.
Attn: @rwjblue
> Expose registry methods from isolatedContainer without deprecations.

- lib/ember-test-helpers/test-module-for-component.js
- tests/test-module-for-component-test.js
We found this issue when upgrading ember-cli to 0.1.15
It seems that a change introduced in the new version of ember-test-helpers causes our component tests to fail because the element is no longer in the DOM when the `willDestroyElement` hook is called.
We use a jquery ui datepicker component that cleans itself up in the `willDestroyElement` hook, but now when we run the tests the jquery ui datepicker code errors because it can't destroy the datepicker on the component's element. 
In `test-module-for-component.js` a teardown is added to `teardownSteps` that destroys the containing view:
https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-component.js#L41
but it looks like that teardown is added after `teardownTestElements` in …
> Component not in dom in willDestroyElement

- .bowerrc
Bower components were installing into `app/bower_components` due to a mysterious `.bowerrc` file higher up in my file system. `npm start' would fail because bower-components were not being found. This makes sure bower components will be installed where broccoli expects them.
> make sure bower_components folder is where broccoli expects

- lib/ember-test-helpers/test-module.js
- tests/test-module-test.js
I'm not sure what there is to test here so I didn't add any tests yet. 
Currently the container is destroyed which takes care of destroying any dependencies brought in by `needs` but the subject is never properly town down. This makes sure that happens.
> destroy the subject in teardown

- lib/ember-test-helpers.js
- lib/ember-test-helpers/test-module-for-integration.js
- tests/test-module-for-integration-test.js
This adds a new kind of test module that fills a gap in the current set of possible tests. So far we have:
- unit tests that are good for testing algorithmic correctness in isolation.  
- acceptance tests that are good for testing within a complete application.
But we're missing the ability to integration test a unit smaller than whole-application. This PR adds a new `TestModuleForIntegration` that lets you drive an integration test with a template. I think this is often a more appropriate way to test Ember Components than a unit test, because interesting components tend to have rich dependence on other components.
The included tests illustrate the basic use cases: rendering a template, setting values in its context, and handling its events.
> Adding standalone integration test support

- lib/ember-test-helpers/isolated-container.js
When the `Registry` is present, its `normalizeFullName` method should be
set to the resolver's `normalize` method.
Overriding the normalize methods on the container is ineffective because
they need to proxy to the associated registry's methods.
> Set `registry.normalizeFullName` to `resolver.normalize`.

- lib/ember-test-helpers/test-module-for-integration.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-test.js
This moves the integration logic up into TestModule, so that you can specify:
```
integration: true
```
And you'll be able to resolve other units in your application without adding them to `needs`.
(thanks @rwjblue!)
> Move integration container logic to TestModule

- lib/ember-test-helpers/test-module-for-component.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-for-component-test.js
from #26 
This PR makes two changes:
* use a `cachedCalls` object internally in TestModule to track whether a given callback has been called. Previously, the code only did a check on the result (in `this.cache[key]`), which means that a callback that returns a falsy value will (incorrectly, it seems) be called multiple times. This seemed likely to result in inconsistent behavior. (This change is necessary for the following change)
* change `this.callbacks.render` to *not* return anything. It simply renders the component. This is a _breaking change_. Previously, `render` would return the rendered view's `this.$()` method, but this is problematic because there are cases where a view's `$()` method should not be called. Specifically, in Ember 1.11.0.beta-5, calling `this.$()` on a tagless …
> [breaking] Remove `view.$()` call in `render()` of module for component

- lib/ember-test-helpers/test-module-for-model.js
- tests/test-module-for-model-test.js
Previously, the `container` was shared across each module (NOT each test) inside `this.subject()` and `this.store()`.
This ensures that those callbacks grab the `container` for each test run (instead of using the closure scope variable).
Credit to @bmac for tracking down the cause, and providing a reliable test reproduction.
> Ensure `moduleForModel` uses the correct store for `subject`.

- lib/ember-test-helpers/isolated-container.js
This will make it easier to test serializers without having to know
about the transform's Ember Data registers under the hood.
Not sure the best way to test this without adding Ember Data as a dependency.
> Register some built in Ember Data objects if ED exists on the page.

- lib/ember-test-helpers/test-module.js
- tests/test-support/qunit-module-for.js
This makes it possible for module hooks to be asynchronous.
My immediate use case for this is that the only way to do an asynchronous action in a mocha `beforeEach` hook is to return a promise from said hook.
I'm submitting corresponding PRs to ember-mocha and ember-qunit.
> Asynchronous module hooks

- lib/ember-test-helpers/isolated-container.js
- lib/ember-test-helpers/test-module-for-model.js
This pr will automatically register the Store as a service for users running. Ember Data beta.16.
The one gotcha is if the user declares `service:store` in their needs. For Example: 
```js
moduleForComponent('actor-table', {
// specify the other units that are required for this test
needs: ['service:store']
});
```
The test will blow up with this error. `Uncaught TypeError: Attempting to register an unknown factory: 'service:store'`, because this code https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/isolated-container.js#L81-L85 attempts to pull in a `service:store` from `app/services/store.js` which likely doesn't exist.
> Delegate to DS._setupContainer when available to register service:store

- lib/ember-test-helpers/isolated-container.js
This is getting pretty annoying. We need a *much* better way to deal with these default/fallback container items, but we also need tests to work in Glimmer-land.  So, grrr, but YOLO...
> Add container items required for Glimmer.

- lib/ember-test-helpers/test-module-for-component.js
- tests/test-module-for-component-test.js
> Allow missing arguments for `moduleForComponent`.

- lib/ember-test-helpers/test-module-for-component.js
- tests/test-module-for-component-test.js
> Ensure moduleForComponent with description works.

- Brocfile.js
- bower.json
- lib/ember-test-helpers/test-module-for-component.js
- tests/test-module-for-component-test.js
- tests/test-module-for-integration-test.js
- tests/test-support/qunit-test.js
- tests/test-support/resolver.js
This cleans up deprecations for use with Ember 1.13+, plus one small
private API break (the changed `Resolver.create()` call).
The removed tests were all testing container resolution of things that
are deprecated. There is still coverage for container resolution of
Components, which should be sufficient.
The test suite still emits a several deprecations, but they are all
coming from Ember Data and will need to get fixed there.
I worked on this PR with @stefanpenner.
This PR also supersedes #42, which was ready to go and relevant.
> Compatibility with Ember 1.13+

- config/ember-try.js
- tests/test-module-for-component-test.js
This replaces the `{{view}}` helper test coverage that I removed in #60 with a test of the `{{component}}` helper instead.
This makes the test suite incompatible with Ember 1.10, which seems reasonable given that we've now released 1.13, so the list of supported releases remains the same length.
> Add a test for {{component}} helper

- lib/ember-test-helpers/build-registry.js
- tests/test-module-for-integration-test.js
This fixes another deprecation in Ember 1.13. ember-test-helpers was
replacing `view:toplevel` with `Ember.View`, which is deprecated. We
should instead just leave `view:toplevel` alone, because the internal
version is not deprecated.
> Don't replace Ember's internal view:toplevel

- lib/ember-test-helpers/test-module.js
https://github.com/emberjs/ember.js/pull/11459 marks `Ember.keys` for deprecation in favor of Object.keys.
> Ember.keys is deprecated in favor of Object.keys

- lib/ember-test-helpers/test-module.js
- tests/test-module-for-component-test.js
When there are exceptions in the setup steps (for example needs component missing)
the implementation is not properly capturing those exceptions.
This fix uses the slighlty longer syntax for creating promises which
wraps the call in a function and allows RSVP to properly capture
the exception. When using the shorter RSVP.resolve() form the exception
happens outside (before) the RSVP invocation and cannot be captured.
> Guard against exceptions in the setup steps.

- lib/ember-test-helpers/test-module-for-component.js
- tests/test-module-for-integration-test.js
> allow getProperties and setProperties for component integration tests

- lib/ember-test-helpers/build-registry.js
The intent of this code initially was to suppress deprecation messages that could not be fixed by the test suite.
In Ember 2.0.0 these deprecated methods are being removed, this change ensures that we only expose them when the container already has them.
See https://github.com/emberjs/ember.js/pull/11853 for details.
> Only override container methods if present.

- lib/ember-test-helpers/test-context.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-test.js
> ensure we correctly cleanup the context

- bower.json
- config/ember-try.js
- package.json
Tried upgrading to patch memory leaks, our tooling freaked out because it attempted to pull stuff from outside the fire wall that is not needed for runtime.
> Remove dependencies that are actually dev dependencies

- lib/ember-test-helpers/test-module-for-component.js
- lib/ember-test-helpers/test-module.js
Internally, the `EventDispatcher` looks for the global view registry on the container and then falls back to using `View.views`. Since we were creating it directly instead of via the container, it had no container reference, and so it was doing all view tracking using the fallback. 
This is problematic, because the global fallback path is now only accessible from inside Ember (by design, because we're trying to eliminate it.)
> Consistently use the new view registry

- lib/ember-test-helpers/test-module-for-component.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-for-component-test.js
> Ensure view-registry is injected for unit tested components.

- lib/ember-test-helpers/test-module.js
- tests/test-module-test.js
`needs` will switch off integration testing, this is not obvious. If
both are declared we should throw a descriptive Error.
> Throw when integration and needs declared

- tests/test-module-for-model-test.js
Silences the following deprecation:
DEPRECATION: Passing classes to store methods has been removed.
Please pass a dasherized string instead of undefined
[deprecation id: ds.store.passing-classes-deprecated]
> [BUGFIX] Pass in model name to `store.adapterFor`

- lib/ember-test-helpers/build-registry.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-test.js
By default in Ember things that are automatically resolved take precedence over things that are manually registered. This is somewhat counterintuitive to many people, as they would like to be able to override a service or other factory in a given set of tests (for example to use a mock analytics service).
The ability to do this has existed since the SSR/Fastboot work that split the registry from the container in 1.11, but I only recently realized how I could leverage that work here.
This change adds new functionality on Ember 1.11+, but allows older versions to continue to work as they do today (aka non-breaking).
---
Example:
Assuming you have a `app/services/analytics.js` and want to use a mock service for a set of component integration tests, you might do something like this: …
> Allow overriding services/factories in the registry.

- lib/ember-test-helpers/test-module.js
Fixes a typo in the error message when declaring both `integration: true` and `needs` in the same module
> Fix typo in thrown error

- lib/ember-test-helpers/test-module-for-component.js
This fixes canary, where "controller" no longer works to redirect actions. Fixes #99.
> Move action handling from module to context

- lib/ember-test-helpers/has-ember-version.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-for-component-test.js
- tests/test-module-for-integration-test.js
Versions of Ember prior to 1.13 require a full router booted by the app, or no router at all. This ensures they receive no router at all instead of the 1.13-safe one. Result is that the link-to helper can be used in Ember 1.11 and 1.12 component tests (unit and integration).
See also these PRs that attempted to fix the issue in Ember:
* https://github.com/emberjs/ember.js/pull/11829
* https://github.com/emberjs/ember.js/issues/11825
IMO, it is more appropriate that it be fixed here, since ember-test-helpers is basically dealing with fragile/intimate API surface when it sets up a router in the container.
> Do not register a router service for Ember <1.13

- lib/ember-test-helpers/test-module-for-component.js
As of Ember 2.1.0, calling `Ember.deprecate` without an options hash including `id` and `until` will actually trigger another deprecation.
This adds the required properties to `Ember.deprecate`'s options hash.
> Add `id` and `until` to deprecations.

- lib/ember-test-helpers/test-module.js
- tests/test-module-for-integration-test.js
- tests/test-module-test.js
In an app, we encourages users to use injection over container.lookup,
and we encourage `application.register` over `registry.register`. But in our integration tests, there is no good alternative to direct `this.container.lookup` and `this.registry.register`.
So I added `register` and `inject` capability directly to the integration test context. `register` is fairly trivial:
```js
test('registering something', function(assert) {
this.register('component:x-foo', Ember.Component.extend({
classNames: ['i-am-x-foo']
}));
this.render(hbs`{{x-foo}}`);
assert.equal(this.$('.i-am-x-foo').length, 1, 'found x-foo');
});
```
`inject` lets you inject anything into the test context:
```js
test('injecting a service', function(assert) {
this.inject.service('notifications'); …
```
> Add public API for injection & registration

- config/ember-try.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-for-component-test.js
- tests/test-module-for-integration-test.js
- tests/test-module-test.js
This is not present on Ember < 1.10.
Also, update ember-try config for Ember 1.10 support.
> Guard for missing Ember.inject.

- lib/ember-test-helpers/test-module-for-component.js
- tests/test-module-for-integration-test.js
Currently,   [component.destroy()](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-component.js#L211)  is only run after  #ember-testing DOM element is [emptied](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module.js#L188). When the component which use third party library  like jquery-ui  or bootstrap javascript component do cleanup using  willDestroyElement() hook, it cannot cleanup properly  because the element is already removed from DOM. In additional , teardownStep should be run in reverse order as setupSteps in general. So this PR also fix the [_resetViewRegistry()](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-component.js#L55) hook in …
> prepend tear down steps like tearDownForComponent in the begining of tearDownSteps array

- Brocfile.js
- bower.json
- lib/ember-test-helpers/test-module.js
- lib/ember-test-helpers/wait.js
- tests/wait-test.js
This allows component integration tests that need to deal with async interactions to have an easy way to model their tests.
Example test (assuming the component does some async in an action triggered by the button click):
```javascript
import { moduleForComponent, test } from 'ember-test-helpers';
import wait from 'ember-test-helpers/wait';
test('it works when async exists in an event/action', function(assert) {
this.render('{{my-foo}}');
this.$('button').click();
return wait()
.then(() => {
// assertions for after async behavior
});
});
```
The guts of this `wait` helper are pulled from the `wait` acceptance test helper in Ember itself. Eventually we may be able to make Ember itself provide an implementation that we can share here and in the acceptance testing world.
> Add `wait` helper.

- lib/ember-test-helpers/build-registry.js
- tests/test-module-test.js
When Ember internally builds a registry via `Ember.Application.buildRegistry` it aliases `registry.normalizeFullName` to `resolver.normalize` and this becomes the fallback registry.  Then Ember creates the primary registry (in `ApplicationInstance`'s constructor) and provides the primary registry's resolver (which is `function() { }` to allow for registration overrides) with the original (aka from the `fallback` registry) `normalizeFullName`.
Unfortunately, when this was initially implemented in ember-test-helpers I missed this nuance and we subsequently had many issues reported for things that the normalize method would have fixed (specifically converting `service:fooBar` to `service:foo-bar` before looking up).
It would be better IMO if `Ember.Registry` could be made aware of this …
> Fix issues with normalization in primary (non-fallback) registry.

- .travis.yml
- Brocfile.js
- lib/ember-test-helpers/build-registry.js
- lib/ember-test-helpers/test-module.js
- package.json
- tests/test-module-test.js
* Allows usage of ES6 syntax.
* Remove usage of broccoli-static-compiler.
* Use ember-getowner-polyfill's `fake-owner` to build a mock owner (since there is no way create an owner directly).
* Add tests confirming that `Ember.getOwner` can be used on instances created through the container.
* Add ability to call `Ember.getOwner(this)` on that test context directly (potentially paving the way to deprecate `this.register`, `this.lookup`, and friends).
> Work with `Ember.getOwner`.

- Brocfile.js
- lib/ember-test-helpers/build-registry.js
- package.json
This is much less brittle than relying on the polyfill for forward/future support.
> Use newly exposed mixins to create owner.

- lib/ember-test-helpers/test-module-for-component.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-for-integration-test.js
This semantics of the `integration` flag have changed in a backwards-incompatible way since v0.4.3.  This corresponds to an ember upgrade (using ember-cli) between v1.12 and v1.13.
In order to ease this upgrade path for ember-cli users, `integration: 'legacy'` will set up a component test with v0.4.3 semantics.  Of course, newer tests would still be encouraged to be written with `integration: true`.
---
Replacement PR for https://github.com/switchfly/ember-test-helpers/pull/115.
/cc @hjdivad
> Add support for `integration: 'legacy'`

- bower.json
- config/ember-try.js
- lib/ember-test-helpers/test-module-for-component.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-test.js
The meaning of `integration: true` has been the same for non-component
tests, so only allow usage of `legacy` when using a component test.
---
Update default dependencies & ember-try config.
* Update default dependencies (makes `ember test` run against current
release).
* Add 2.1.0 to ember-try config.
* Add 2.2.0 to ember-try config.
* Use associated Ember Data with each respective Ember release.
> Restrict integration: 'legacy' to component tests.

- lib/ember-test-helpers/test-module.js
> Fix registry resolver for isolated container @2.3+

- lib/ember-test-helpers/test-module-for-component.js
The outcome of [#38][38] is undocumented. 
Raising a deprecation warning for calls to `this.subject` is a good start, 
but could be improved greatly.
[38]: https://github.com/switchfly/ember-test-helpers/pull/38
> Provide better context for `subject()` deprecation

- lib/ember-test-helpers/test-module-for-component.js
- tests/test-module-for-integration-test.js
> Return passed in value for set and setProperties in integration test

- lib/ember-test-helpers/test-module.js
- tests/test-module-test.js
Addresses #133.
One note: in the case where a user-defined context property collides with a property on the test module, nothing special is done since the user-defined value isn't added to the context until after binding the callbacks.
> Change callback context to deprecate test module properties

- config/ember-try.js
- lib/ember-test-helpers/build-registry.js
Credit for fix code goes to @rwjblue, I am merely the humble PR creator.
This addresses emberjs/data#4071.
> Make build-registry work correctly when ember-data addon is used

- lib/ember-test-helpers.js
- lib/ember-test-helpers/abstract-test-module.js
- lib/ember-test-helpers/test-module-for-acceptance.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-for-acceptance-test.js
- tests/test-support/qunit-module-for.js
- tests/test-support/resolver.js
Currently the behavior necessary for starting and tearing down Ember apps in tests is located in [blueprints](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/tests/helpers/module-for-acceptance.js). Blueprints expose the user to complexity and create extra boilerplate.
Create a `TestModuleForApplication` helper. This:
1. avoids the use of blueprints
2. gives the ember team a natural way to pass testing improvements down to users
3. prevents the user from accessing the `testApp` directly in an acceptance test
4. brings hooks for writing tests to a single location. This improves documentation and creates a stronger separation of concerns between blueprints and tests
First we pulled out a  `AbstractTestModule`. This is a place to put shared behavior between …
> Add moduleForAcceptance

- lib/ember-test-helpers/test-module-for-model.js
Replaces https://github.com/switchfly/ember-test-helpers/pull/142.
> Avoid using DS.JSONAPIAdapter if module is present.

- lib/ember-test-helpers/wait.js
- tests/wait-test.js
Adds support for Ember Test registered waiters (http://emberjs.com/api/classes/Ember.Test.html#method_registerWaiter)
See #139
> Add support for Ember Test registered waiters to wait helper

- lib/ember-test-helpers.js
- lib/ember-test-helpers/abstract-test-module.js
- lib/ember-test-helpers/test-module-for-integration.js
- tests/test-module-for-component-test.js
- tests/test-module-for-integration-test.js
This PR moves component integration testing behavior into its own module named (unsurprisingly :smile:) `TestModuleForIntegration`. This new module now depends on `AbstractTestModule` instead of `TestModule` thus removing boilerplate. Additionally, the new module doesn't contain behavior associated with 'legacy' and unit tests.
> Add moduleForIntegration

- ember-cli-build.js
In regards to #150, this should fix the path issue.  However, there seems to be subsequent ember-data related issues.  @rwjblue I bower installed (without saving) ember-data and that addressed those issues only to be left with some `assert.async` related issues.  I figured I'd PR this change and see what happens.  Granted, the tests still won't pass.
> Use new path to loader.js

- lib/ember-test-helpers/abstract-test-module.js
See: http://emberjs.com/blog/2016/04/11/ember-2-5-released.html#toc_code-ember-assign-code
> Prefer Ember.assign over Ember.merge

- config/ember-try.js
- lib/ember-test-helpers/test-module-for-component.js
- tests/test-module-for-component-test.js
Previously, calling `this.render` twice within the same test (without calling `this.clearRender()` in between) would cause any components created in the first render to never be destroyed (and therefore they cannot cleanup any listeners they created).
This change essentially ensures that we call `clearRender` before each `this.render` invocation so that if a component had been previously instantiated it is cleared and reset.
Fixes #111.
> Ensure prior render is cleared when calling `this.render`.

- config/ember-try.js
- lib/ember-test-helpers/-legacy-overrides.js
- lib/ember-test-helpers/test-module-for-component.js
- lib/ember-test-helpers/test-module.js
- lib/ember-test-helpers/wait.js
- tests/test-module-for-component-test.js
- tests/test-module-for-integration-test.js
Setting context or controller on an Ember.Component was absolutely not supposed to work (ever), but this library worked around that to serve its own needs when Ember.View was deprecated and removed.
This PR makes `moduleForComponent` work properly against canary (soon to be 2.7.0), by avoiding this archaic concept and using normal outlet system.
> Refactor `moduleForComponent` rendering to use outlet system.

- lib/ember-test-helpers/-legacy-overrides.js
- lib/ember-test-helpers/test-module-for-component.js
- tests/test-module-for-component-test.js
Ensures that `this.$()` from within a test represents the same structure as prior versions.
Ultimately, I would prefer for `this.$()` to refer to the inner HTML (basically what is rendered by the template provided to `this.render`), but changing the underlying structure is definitely not good without proper messaging (and likely major version bump).
Fixes #159.
> Fix regression related to DOM structure.

- lib/ember-test-helpers/test-module-for-integration.js
This was fixed in `module-for-component` in https://github.com/switchfly/ember-test-helpers/pull/158.
> Fix the module-for-integration tests on Ember canary.

- lib/ember-test-helpers.js
> export unsetContext from the main module

- config/ember-try.js
- lib/ember-test-helpers/test-module-for-component.js
* Add alpha to ember-try setup.
* Ensure component integration tests instantiate templates through the container.
> Start working on making the alpha pass.

- lib/ember-test-helpers/test-module-for-component.js
- lib/ember-test-helpers/test-module-for-integration.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-for-component-test.js
- tests/test-module-for-integration-test.js
- tests/test-support/resolver.js
This fixes `clearRender` within an integration test (and should make `ember g component foo-bar && ember test` work out of the box).
> More alpha work.

- lib/ember-test-helpers/test-module-for-component.js
- lib/ember-test-helpers/test-module-for-integration.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-for-integration-test.js
- tests/test-module-test.js
- tests/test-support/resolver.js
Addresses #173. After implementing, I realize this could potentially break some one that has already been using the `resolver` property in their passed in environment, but I think that risk is acceptable.
> Introduce resolver option to test module

- tests/test-module-for-component-test.js
The component unit test for `willDestroyElement` is failing due to an issue with Ember 2.9-beta (and canary) where willDestroyElement is triggered after the component has been transitioned to the `destroying` state (and therefore has no element).
Will be working on this upstream to fix, but this demonstrates that the remainder of the tests (including component unit tests) are passing on beta and canary.
> Fix the build (skipping a willDestroyElement test) for canary builds.

- lib/ember-test-helpers/abstract-test-module.js
- tests/test-module-test.js
> Reset ember-testing div to initial state on teardown

- lib/ember-test-helpers/abstract-test-module.js
- tests/test-module-for-acceptance-test.js
- tests/test-module-for-component-test.js
- tests/test-module-for-integration-test.js
- tests/test-module-for-model-test.js
- tests/test-module-test.js
A fix for: https://github.com/emberjs/ember-qunit/issues/247
In an integration test where a component is instantiated the test is the outside context.  Ember when makes an assertion at that point the test is the object that ember is using in the assertion object hench `test.toString()` returns `[object Object]` not a helpful error.
After this PR for this test: 
```js
moduleFor('component:x-foo', 'component:x-foo -- callback context', { ...
this.toString() >> 'test for:  component:x-foo'
```
```js
moduleForAcceptance('TestModuleForAcceptance | Basic acceptance tests', { ...
this.toString() >> 'test for: TestModuleForAcceptance | Basic acceptance tests'
```
```js
moduleForIntegration('Component Integration Tests', { ...
this.toString() >> 'test for: Component Integration Tests'
```
```js …
```
> Overriding toString() to return the test subject name

- ember-cli-build.js
- lib/ember-test-helpers/abstract-test-module.js
- lib/ember-test-helpers/build-registry.js
- lib/ember-test-helpers/test-module-for-acceptance.js
- lib/ember-test-helpers/test-module-for-component.js
- lib/ember-test-helpers/test-module-for-integration.js
- lib/ember-test-helpers/test-module-for-model.js
- lib/ember-test-helpers/test-module.js
- package.json
- tests/test-module-for-component-test.js
- tests/test-module-for-integration-test.js
- tests/test-module-for-model-test.js
- tests/test-module-test.js
- tests/test-support/qunit-module-for.js
- tests/test-support/resolver.js
- tests/wait-test.js
/cc @trentmwillis @rwjblue @dgeb @stefanpenner
> Replace "klassy" with ES6 classes

- README.md
It was still written with the deprecated `setup` and `teardown` callbacks.
> Update QUnit module example

- lib/ember-test-helpers/build-registry.js
- lib/ember-test-helpers/test-module-for-component.js
- lib/ember-test-helpers/test-module-for-integration.js
- lib/ember-test-helpers/test-module-for-model.js
- lib/ember-test-helpers/test-module.js
Ember 2.12 introduces `container.factoryFor()` as a public API and deprecates `container.lookupFactory()`.
This change silences the deprecation warning and retains backward compatibility with Ember 2.11 and earlier.
It introduces one breaking change, which is that unit tests will fail if they do not provide all services injected into the class under test. An error will be thrown during object creation when calling `this.subject()`. Previously, these missing dependencies would be silently ignored.
Tests failing for this reason would need to be updated to add the service dependency to `needs` or to register a stub service in `beforeEach`.
IMHO this is acceptable, and perhaps even preferable to the prior behavior.
> Ember 2.12: Use factoryFor instead of lookupFactory, if available

- lib/ember-test-helpers/test-module-for-component.js
- tests/test-module-for-component-test.js
- Fix `moduleForComponent` unit test deprecation being raised even if `needs` is provided.
- Add a test case.
Fixes: #195
> Deprecation Warning thrown with `needs:[]`

- lib/ember-test-helpers/build-registry.js
- lib/ember-test-helpers/test-module-for-model.js
Relying on global `require` calls causes issues in babel@6.
> Import `require` (avoid using global require).

- lib/ember-test-helpers/abstract-test-module.js
- lib/ember-test-helpers/ext/rsvp.js
- lib/ember-test-helpers/test-module.js
- tests/test-module-for-component-test.js
This is essentially doing the same thing that was added way back in Ember 1.6/1.7 by Stef.
The basic gist is that whenever something is triggering RSVP's `async` it will wrap that in a `Ember.run`. This prevents folks from getting the autorun error for just resolving promises...
This brings the ember-metal-test-friendly-promises feature (from https://github.com/emberjs/ember.js/pull/4176) to ember-test-helpers.
> Ensure RSVP promises do not need manual Ember.run wrapping.

- addon-test-support/test-module-for-component.js
This allows `ember-native-dom-event-dispatcher` to be registered and hence unit tests to run without jQuery.
> Autoregister event dispatcher in unit tests

- .travis.yml
- config/ember-try.js
- ember-cli-build.js
- package-lock.json
- package.json
- tests/dummy/app/templates/application.hbs
- tests/helpers/events.js
- tests/helpers/has-jquery.js
- tests/helpers/resolver.js
- tests/unit/test-module-for-acceptance-test.js
- tests/unit/test-module-for-component-test.js
- tests/unit/test-module-for-integration-test.js
- tests/unit/test-module-for-model-test.js
- tests/unit/wait-test.js
* add test scenarios that run without jQuery (defaulting to jQueryless setup)
* refactor all tests to avoid jQuery usage
* embed custom eventing test helpers (until we can bring ember-native-dom-helpers into the fold)
> Reduce direct jQuery usage in tests.

- tests/helpers/events.js
- tests/unit/setup-context-test.js
- tests/unit/setup-rendering-context-test.js
Carries over many tests from the previous (now "legacy-0-6-x" suite) into the new system. This is largely to ensure that the regressions previously caught by these tests, are still checked for long after the legacy-0-6-x suite is gone.
> Continue to flesh out more tests for new API's.

- addon-test-support/index.js
- addon-test-support/setup-rendering-context.js
- tests/unit/setup-rendering-context-test.js
These functions can be used instead of repeating `this.` throughout the testing code.
Example:
```js
import { module, test } from 'qunit';
import { setupRenderingTest, render, element } from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';
module('x-foo', function(hooks) {
setupRenderingTest(hooks);
test('renders', async function(assert) {
assert.expect(1);
await render(hbs`{{pretty-color name="red"}}`);
assert.equal(element.querySelector('.color-name').textContent, 'red');
});
});
```
This is essentially the compromise made with the rest of the core team while working on the the "Grand Unified Testing RFC". The helpers will continue to live on `this` (for easy discoverability), but are also importable (for cleaner looking tests). Using the non `this.` form of helpers …
> Expose importable helper functions.

- README.md
Still fairly weak, but its a good start.
> Update README for new API iteration.

- addon-test-support/setup-rendering-context.js
- tests/unit/settled-test.js
- tests/unit/setup-rendering-context-test.js
- tests/unit/teardown-rendering-context-test.js
Prior to this change, the `innerHTML` of the `#ember-testing` element was reset after each test (much in the same way as QUnit itself resets the `#qunit-fixture` between tests). There were two specific issues with the approach:
1. The `teardownRenderingContext` was **required** to run after the `teardownContext`. If the order was set correctly (`teardownRenderContext(this)` _then_ `teardownContext(this)`) errors would be thrown because Ember is attempting to clean up the rendering engine and its expected DOM elements to remove are no longer present. This meant that we could not use the normal rule of thumb for these things: that teardown is done in the reverse order of setup.
2. Any attributes or properties added to the `#ember-testing` element were **not** being cleaned up, and caused a …
> Ensure testing elements are properly reset/cleared.

- addon-test-support/index.js
- addon-test-support/legacy-0-6-x/abstract-test-module.js
- addon-test-support/setup-context.js
- addon-test-support/teardown-context.js
- tests/helpers/module-for-acceptance.js
- tests/helpers/qunit-module-for.js
- tests/test-helper.js
- tests/unit/legacy-0-6-x/test-module-for-component-test.js
- tests/unit/setup-context-test.js
- tests/unit/teardown-context-test.js
Previously, `Ember.testing` was set to `true` in module scope of `ember-test-helpers` module. This causes issues due to how Ember handles RSVP promises that happen while `Ember.testing` is truthy.
This commit updates the various machinery to set `Ember.testing = true` when tests are starting, and reset it to `false` once they've finished their teardown. It also adds assertions to ensure that each test properly cleans up after itself.
Note: In some cases, instead of adding new assertions I used `throw new Error()`. This was only done in the "legacy" tests as a way of ensuring the required functionality without modifying all `assert.expect()` counts throughout those test files.
Partially addresses https://github.com/emberjs/ember-qunit/issues/246.
> Set Ember.testing only while actually running a test.

- addon-test-support/legacy-0-6-x/abstract-test-module.js
- addon-test-support/setup-rendering-context.js
- tests/index.html
- tests/test-helper.js
- tests/unit/legacy-0-6-x/test-module-test.js
The changes made in 7ad93d2c introduced a bug in the way that the testing DOM is cleaned up between tests. The error was quite simple: we were storing the `storedValue = container.outerHTML` before starting the test then resetting `container.innerHTML = storedValue`.  This created a DOM node leak for each test processed.
This fixes the issue for both the new testing API's in 0.7 and the older pre-existing system. It also adds some post-test checks to ensure that the DOM is indeed what we expect after each test is completed.
Fixes #228.
> Ensure ember-testing-container is reset properly.

- addon-test-support/index.js
- addon-test-support/setup-context.js
- tests/unit/setup-context-test.js
This is the base implementation to allow for `pauseTest()` functionality. These methods are designed to be wrapped by the host test framework so that any test timeouts are properly configured to avoid the test "failing" while being interacted with.
> Add pauseTest and resumeTest functionality.

- addon-test-support/setup-context.js
- addon-test-support/setup-rendering-context.js
- addon-test-support/teardown-context.js
- addon-test-support/teardown-rendering-context.js
- tests/unit/settled-test.js
- tests/unit/setup-context-test.js
- tests/unit/setup-rendering-context-test.js
- tests/unit/teardown-context-test.js
- tests/unit/teardown-rendering-context-test.js
Most of the changes in this PR are whitespace/indentation changes. https://github.com/emberjs/ember-test-helpers/pull/236/files?w=1 is much easier for reviewing the _actual_ changes.
Fixes https://github.com/emberjs/ember-test-helpers/issues/235
> Make setup and teardown of new API async.

- addon-test-support/application.js
- addon-test-support/build-owner.js
- addon-test-support/index.js
- addon-test-support/legacy-0-6-x/build-registry.js
- addon-test-support/resolver.js
- addon-test-support/setup-context.js
- addon-test-support/setup-rendering-context.js
- tests/dummy/app/resolver.js
- tests/helpers/resolver.js
- tests/unit/setup-context-test.js
- tests/unit/setup-rendering-context-test.js
When the host project properly registers their application, the testing context will now boot a lightweight instance of the application (similar to what FastBoot does).
In this scenario both `initializers` and `instance-initializers` will run so no more manual initializer setup shenanigans (as [documented here fore mirage](http://www.ember-cli-mirage.com/docs/v0.3.x/manually-starting-mirage/)). This has been a very long standing point of confusion for folks while testing, and I'm **very** excited to finally have a path forward that is both performant and intuitive.
For those curious, `initializers` will run only once for the entire test suite (unlike acceptance tests prior to https://github.com/emberjs/rfcs/pull/268), and the `instance-initializers` will run once per test (which also …
> Use `Application.create().buildInstance()` if possible.

- addon-test-support/@ember/test-helpers/application.js
- tests/helpers/resolver.js
- tests/unit/application-test.js
This allows an application to call:
```js
setApplication(App.create({ autoboot: false }));
```
And still support legacy style `moduleFor*` tests.
Without this change the following both of the following invocations are required:
```js
setApplication(App.create({ autoboot: false }));
setResolver(resolver);
```
> Automatically set resolver when `setApplication` is called.

- README.md
- addon-test-support/@ember/test-helpers/index.js
- addon-test-support/@ember/test-helpers/validate-error-handler.js
- tests/unit/validate-error-handler-test.js
Ensures that `Ember.onerror` is setup that properly re-throws when testing.
This is intended to be used by test framework hosts (or other libraries) to ensure that `Ember.onerror` is properly configured. Without a check like this, `Ember.onerror` could _easily_ swallow all errors and make it _seem_ like everything is just fine (and have green tests) when in reality everything is on fire...
Example implementation for `ember-qunit`:
```js
import { validateErrorHandler } from '@ember/test-helpers';
test('Ember.onerror is functioning properly', function(assert) {
let result = validateErrorHandler();
assert.ok(result.isValid, result.message);
});
```
Additional reading:
* more detailed writeup in https://github.com/emberjs/ember.js/pull/15871
* …
> Implement `validateErrorHandler` utility.

- addon-test-support/@ember/test-helpers/index.js
- addon-test-support/@ember/test-helpers/settled.js
This is a simple refactoring of the existing `settled` helper that exposes an `isSettled()` function which can be used generally to confirm that there are is no pending async.
One example use case is for `ember-qunit` (and also `ember-mocha`) to implement something like:
```js
import { isSettled } from '@ember/test-helpers';
QUnit.testDone(function(results) {
if (!isSettled) {
throw new Error(`${results.name} leaks async`);
}
});
```
> Expose `isSettled` utility function.

- addon-test-support/@ember/test-helpers/teardown-context.js
- tests/test-helper.js
- tests/unit/legacy-0-6-x/test-module-for-acceptance-test.js
- tests/unit/legacy-0-6-x/test-module-for-component-test.js
- tests/unit/legacy-0-6-x/test-module-test.js
- tests/unit/setup-context-test.js
- tests/unit/teardown-context-test.js
* Refactor cleanup assertions to use global failure after test run.
* Avoid `before` and `after` when randomizing test order.
* Ensure `setupRegistry` is called _before_ it is needed each time.
* Simplify precondition assertion in test-module-for-acceptance tests.
* Make randomized seed testing easier.
* Ensure `unsetContext()` is called during teardown.
> Fix order dependence in tests.

- tests/unit/legacy-0-6-x/test-module-for-component-test.js
It has been long deprecated, and is removed in Ember 3.0 (current canary builds).
> Remove usage of Ember.Handlebars.SafeString.

- .travis.yml
The total time for this stage is massively dominated by `yarn install`
time, doing `yarn lint && yarn test` seems better than launching two
CI jobs.
> Run `yarn lint` and `yarn test` from the same job in first stage.

- addon-test-support/@ember/test-helpers/settled.js
> settled: Ramp up timeout values for isSettled() check

- addon-test-support/@ember/test-helpers/settled.js
The code that was added to ensure that all `promise.then` or `promise.catch` callbacks are "flushed" before decrementing the counter (which fixed a number of bugs where `settled` would accidentally become `true` before the promise callbacks themselves could have a chance to run), caused an issue when using the legacy `moduleForComponent` system to render a template that itself kicked off an async request.
Prior to the changes made in this commit, when rendering would kick off async (e.g. rendering a `{{parent.child}}` style path referencing an ember-data async relationship) there would _already_ be an existing `Ember.run.backburner.currentInstance` (which was created by the `RSVP.Promise.resolve().then(...)` being removed in this commit) which ultimately forced us down the path that meant …
> Refactor settled to avoid triggering a new run-loop.

- addon-test-support/@ember/test-helpers/settled.js
- index.js
- tests/helpers/module-for-acceptance.js
- tests/integration/module-for-acceptance-interop-test.js
- vendor/monkey-patches.js
Ember internally tracks AJAX requests in the same way that we do here for legacy style "acceptance" tests using the `ember-testing.js` asset provided by emberjs/ember.js itself. When `@ember/test-helpers`'s `settled` utility is used in a legacy acceptance test context any pending AJAX requests are not properly considered during the `isSettled` check below.
This utilizes a local utility method present in Ember since around 2.8.0 to properly consider pending AJAX requests done within legacy acceptance tests.
> Wait for pending AJAX in acceptance tests.

- addon-test-support/@ember/test-helpers/-utils.js
- addon-test-support/@ember/test-helpers/settled.js
- addon-test-support/@ember/test-helpers/setup-context.js
- addon-test-support/@ember/test-helpers/setup-rendering-context.js
- addon-test-support/@ember/test-helpers/teardown-context.js
- addon-test-support/@ember/test-helpers/teardown-rendering-context.js
Updates `setupContext` and `setupRenderingContext` to use `nextTickPromise` (simplifying the code nicely).
Also adds `settled()` calls after `render`, `clearRender`, `teardownContext`, and `teardownRenderingContext` to ensure that all run-loop business has been completed before returning.
Fixes https://github.com/emberjs/ember-test-helpers/issues/268.
> Use `nextTick` and `nextTickPromise` throughout codebase.

- index.js
- vendor/monkey-patches.js
Fixes an issue introduced by #264 on IE11.
> Ensure `vendor` is transpiled.

- ember-cli-build.js
By default ember-cli updates a number of the "app trees" to be from `tests/dummy` when developing an addon locally. We do this for `app`, `styles`, `templates`, `public`, and `tests` trees (handled inside `lib/broccoli/ember-addon.js`).
Unfortunately, we do **not** forward the apps `vendor` tree to `tests/dummy/`. This means that our addon's `treeForVendor` is called, but then subsequently _clobbered_ by the "apps" `vendor` tree (which is _literally the same tree_, but untranspiled).
IMHO, this should be fixed in ember-cli upstream. I can't imagine anyone relying on this behavior intentionally...
> Ensure `vendor` tree is transpiled when developing addon.

- addon-test-support/@ember/test-helpers/-utils.js
- addon-test-support/@ember/test-helpers/setup-context.js
- addon-test-support/@ember/test-helpers/setup-rendering-context.js
- addon-test-support/@ember/test-helpers/teardown-context.js
- addon-test-support/@ember/test-helpers/teardown-rendering-context.js
- tests/unit/teardown-rendering-context-test.js
The following are the two cleanup buckets:
* `RENDERING_CLEANUP` is done when `teardownRenderingContext` is done (which should **always** be before `teardownContext` is ran).
* `CLEANUP` is done _after_ everything else is destroyed and settled.
---
This refactor fixes the vast majority of issues on IE11. Prior to these changes we were resetting the DOM test fixtures to their original values _before_ we had properly cleaned up the DOM. This meant that when the DOM cleanup actually does run, the various nodes being removed by glimmer's internal cleanup system are not actually present in DOM.  Apparently, Chrome / FireFox / Safari / Edge are all fine with this situation (and silently allow `node.removeChild(someThingNotInNode)` without an error), but IE11 did properly (IMHO) error that …
> Split cleanup into two buckets.

- addon-test-support/@ember/test-helpers/dom/fill-in.js
- tests/dummy/config/targets.js
- tests/helpers/is-ie.js
- tests/unit/dom/blur-test.js
- tests/unit/dom/click-test.js
- tests/unit/dom/fill-in-test.js
- tests/unit/dom/focus-test.js
- tests/unit/dom/tap-test.js
- tests/unit/legacy-0-6-x/test-module-for-component-test.js
- tests/unit/teardown-rendering-context-test.js
I think there is still 2 failing tests, but I'm out for the day.
> Fix almost all tests for ie11

- addon-test-support/@ember/test-helpers/index.js
- addon-test-support/@ember/test-helpers/setup-application-context.js
- addon-test-support/@ember/test-helpers/setup-context.js
- addon-test-support/@ember/test-helpers/setup-rendering-context.js
- addon-test-support/@ember/test-helpers/teardown-application-context.js
- tests/helpers/resolver.js
- tests/unit/setup-application-context-test.js
> Add application testing infrastructure.

- tests/helpers/browser-detect.js
- tests/unit/dom/blur-test.js
Mentioned in https://github.com/emberjs/ember-test-helpers/pull/277#pullrequestreview-83972554.
> Cleanup browser detection and overrides.

- addon-test-support/@ember/test-helpers/setup-rendering-context.js
- index.js
- package.json
- tests/integration/setup-rendering-context-test.js
- tests/unit/setup-rendering-context-test.js
Previously (with `moduleForComponent`) eager rendering was avoided because it was not clear that rendering was _actually_ desired (and therefore the extra work would be wasted in cases that were not testing rendering).  Unlike `moduleForComponent` we can be certain that `setupRenderingContext` is only used in actual rendering contexts (its in the name :P ), so we do not need to be concerned with the performance.
This change is a compatible change (unless someone was _relying_ on the fact that `this.element` was undefined, which seems super weird) that ensures `this.element` is set immediately upon `setupRenderingContext` being called (instead of lazily when the first `render` is done). At that point `this.element` is essentially an empty element (roughly akin to having only `{{outlet}}` …
> Refactor `setupRenderingContext` so that element is stable after setup.

- .gitignore
- .npmignore
- .travis.yml
- documentation.yml
- package.json
- yarn.lock
Resolves part of https://github.com/emberjs/ember-test-helpers/issues/285
I haven't tested the CI part yet, but in theory it should be configured so that it automatically builds and deploys the documentation to GitHub Pages whenever a tag is pushed.
Unfortunately http://emberjs.github.io/ember-test-helpers/ is currently directing to a emberjs.com 404 page so I'm not sure if we can actually use GitHub Pages at all 🤔 
/cc @locks
> Add `documentation` dev dependency

- .eslintrc.js
- index.js
- package.json
- yarn.lock
* Add jsdoc validation (warning for now)
* Add eslint-plugin-node (checking `index.js`)
* Fix invalid globs for `index.js`
> Tweak linting configuration.

- .eslintrc.js
- addon-test-support/@ember/test-helpers/dom/fire-event.js
Now that the documentation is updated, this makes it an error...
> Tests: Make valid-jsdoc an error (instead of warning)

- addon-test-support/@ember/test-helpers/settled.js
- addon-test-support/@ember/test-helpers/wait-until.js
Migrates ramp up functionality to `waitUntil` and migrates `settled` to leverage `waitUntil`.
> Refactor settled to leverage waitUntil.

- addon-test-support/@ember/test-helpers/setup-context.js
- addon-test-support/@ember/test-helpers/teardown-context.js
- addon-test-support/ember-test-helpers/legacy-0-6-x/abstract-test-module.js
- addon-test-support/ember-test-helpers/legacy-0-6-x/ext/rsvp.js
As mentioned in the recently updated documentation, this is actually not needed. This commit removes it from the RFC232 style testing harness (only leaving it in place for legacy `moduleFor` style tests in order to have as little churn as possible there).
> Chore: Remove RSVP "resolve in run-loop" config

- addon-test-support/@ember/test-helpers/dom/-get-element.js
- addon-test-support/@ember/test-helpers/dom/get-root-element.js
- addon-test-support/@ember/test-helpers/dom/wait-for.js
- addon-test-support/@ember/test-helpers/setup-rendering-context.js
- tests/helpers/events.js
- tests/integration/settled-test.js
- tests/integration/setup-rendering-context-test.js
- tests/unit/dom/blur-test.js
- tests/unit/dom/click-test.js
- tests/unit/dom/fill-in-test.js
- tests/unit/dom/focus-test.js
- tests/unit/dom/tap-test.js
- tests/unit/dom/trigger-event-test.js
- tests/unit/dom/trigger-key-event-test.js
- tests/unit/dom/wait-for-test.js
Extracts a `getRootElement` utility function (used by `getElement` and `waitFor`).  The utility is private for now, but may be made public in the future (needs more docs at the least).
The basic gist is that `getRootElement` should search relative to the `rootElement` of the application (when `setApplication` was used), and _not_ scoped to the first `.ember-view` _inside_ that element. This ensures that elements added to the `rootElement` (e.g. via `ember-wormhole` / `liquid-wormhole`) can also be interacted with.
Also updates `setupRenderingContext` to use the applications designated `rootElement` (as opposed to _always_ using `#ember-testing`). This brings `setupRenderingContext` in line with `setupApplicationContext`, and now properly uses the specified `rootElement`.
Prior to this, …
> Use "real" rootElement for DOM interaction helpers.

- addon-test-support/@ember/test-helpers/setup-rendering-context.js
Moves core functionality into the importable `render` / `clearRender` / etc utility functions and out of the `setupRenderingContext` directly.
This simplifies how the methods work together (since they no longer have access to _everything_ in closure scope), and sets the stage for an eventual deprecation of `this.render` and `this.clearRender`.
> Clean up and simplify setupRenderingContext

- index.js
When `this.options` is not set on the addon instance, ember-cli-htmlbars-inline-precompile will **not** install the babel plugin on the correct babel instance. This fixes that issue for older ember-cli versions by _always_ ensuring that `this.options` is defined.
> Ensure templates are precompiled properly on ember-cli < 2.12.

- addon-test-support/@ember/test-helpers/dom/fill-in.js
- tests/unit/dom/fill-in-test.js
For cases where you want to clear out an input and such.
> Allow empty string to fillIn

- addon-test-support/@ember/test-helpers/setup-context.js
- tests/unit/setup-context-test.js
The initializers were running after the snapshot of the root element was taken, meaning that if an initializer modified the contents of the root element, that modification would not persist beyond the first test. So we boot the app a little earlier to make sure initializers can safely modify the DOM.
> Make sure initializers can modify the DOM

- .travis.yml
- addon-test-support/@ember/test-helpers/setup-application-context.js
- addon-test-support/@ember/test-helpers/setup-rendering-context.js
- addon-test-support/ember-test-helpers/legacy-0-6-x/test-module-for-component.js
- config/ember-try.js
- package.json
- tests/dummy/config/environment.js
- tests/integration/setup-rendering-context-test.js
- tests/unit/setup-rendering-context-test.js
- yarn.lock
Is this the best way to check if a feature flag is enabled?
> Support testing without an application template wrapper.

- addon-test-support/@ember/test-helpers/settled.js
- addon-test-support/ember-test-helpers/wait.js
- tests/integration/settled-test.js
- tests/unit/wait-test.js
The original goal of `settled` was to "rebrand" `wait` as `settled` without the 'baggage" (since `wait` had some legacy APIs that should not exist in `settled`). Unfortunately, the code refactoring that I had originally done that allowed them to be shared resulted in introducing bugs like those reported in #283.
This commit completely severs the implementation of `wait` from that of `settled`, by leveraging the (IMHO very nice) layers of abstraction that we have created since the original extraction.  Implementing `wait` with `waitUntil` and `getSettledState` makes this quite trivial now.
tldr of changes:
* `isSettled` no longer has to support the legacy `wait` contract (this was undocumented private behavior _only_ kept around to support the old semantics of `wait`)
* `wait` is …
> Remove simple alias for `wait` -> `settled`.

- package.json
- yarn.lock
see https://github.com/documentationjs/documentation/issues/1014
> Lock down documentation to 5.3.5 to avoid Node 4 issues.

- addon-test-support/ember-test-helpers/wait.js
When `wait` was split from `settled` I forgot to also include an infinite timeout (preventing tests from failing that take longer than 2s).
Fixes #318
> Fix regression with `wait()` timeouts.

- addon-test-support/@ember/test-helpers/dom/fire-event.js
- tests/unit/dom/select-files-test.js
Even though ember-test-helpers doesn't have a `selectFiles` helper (yet?) it does handle firing of events with files. However, it was not possible to select files more than once (not to be confused with selecting multiple files at once).
> Add test for firing file change event twice

- API.md
- README.md
- documentation.yml
[Rendered](https://github.com/Turbo87/ember-test-helpers/tree/do-not-install-me#embertest-helpers)
see commit messages
Resolves #333
> Enhance README and API reference

- API.md
- addon-test-support/@ember/test-helpers/index.js
- tests/unit/application-test.js
One use case I have is I would like to call `setApplication(Application.create({ autoboot: false, custom: 'bar' });` or something similar.  However, this may be a bit dangerous because this sets the application for the rest of the test run.  In order to ensure further calls to get the application instance aren't this Application instance, I need to reset it with the old application instance using `this.oldAppInstance = getApplication()` before setting.
Lmk what you think!
Ref #335
> make getApplication public

- addon-test-support/@ember/test-helpers/wait-until.js
- tests/unit/wait-until-test.js
We have need to distinguish between different waitUntil timeouts. To do this, it would be nice to be able to pass a custom error message to waitUntil which it will use upon promise reject. This small PR does that.
> Allow for custom error message in waitUntil helper

- API.md
- addon-test-support/@ember/test-helpers/dom/wait-for.js
> wait-for helper's count value is null by default.

- addon-test-support/@ember/test-helpers/setup-context.js
- addon-test-support/@ember/test-helpers/setup-rendering-context.js
- tests/unit/setup-context-test.js
- tests/unit/setup-rendering-context-test.js
> Protect context properties and methods from overwriting

- addon-test-support/@ember/test-helpers/dom/find-all.js
- addon-test-support/@ember/test-helpers/dom/find.js
- tests/unit/dom/find-all-test.js
- tests/unit/dom/find-test.js
Addresses https://github.com/emberjs/ember-test-helpers/issues/351
> Add `context` argument assertions to the `find` and `findAll` helpers

- API.md
- addon-test-support/@ember/test-helpers/dom/wait-for.js
- tests/unit/dom/wait-for-test.js
Opens up `waitFor` to have a `timeoutMessage`.
> add waitFor msg

- addon-test-support/@ember/test-helpers/dom/fire-event.js
- addon-test-support/@ember/test-helpers/dom/trigger-key-event.js
- tests/unit/dom/trigger-key-event-test.js
Closes #265
Now: `triggerKeyEvent(selector, 'keydown', 9)` and `triggerKeyEvent(selector, 'keydown', 'Tab')` are equivalent.
Also, the generated event in both cases has `e.keyCode === 9` and `e.key === 'Tab'`
> Fix KeyboardEvent#key and allow `triggerKeyEvent` to receive keys instead of keycodes

- addon-test-support/@ember/test-helpers/setup-context.js
- addon-test-support/@ember/test-helpers/setup-rendering-context.js
Test context is shared in Mocha (https://github.com/mochajs/mocha/wiki/Shared-Behaviours), so test specific properties need to be deleted or reconfigured after each test. 
`ember-mocha` currently deletes the properties added. In order to do this it needs them to be `configurable` and `enumerable`.
See https://github.com/emberjs/ember-mocha/issues/205 for more details.
> Change descriptors to allow properties to be enumerated and configured

- .travis.yml
This should fix https://travis-ci.org/emberjs/ember-test-helpers/jobs/380815111 while we're still targeting Node 4 here.
> auto-dist-tag: Use Node 4 compatible release

- addon-test-support/@ember/test-helpers/-utils.js
- addon-test-support/@ember/test-helpers/dom/trigger-key-event.js
- tests/unit/dom/trigger-key-event-test.js
Resolves https://github.com/emberjs/ember-test-helpers/issues/368
/cc @mydea
> Improve `triggerKeyEvent()` warnings

- addon-test-support/@ember/test-helpers/dom/click.js
- tests/unit/dom/click-test.js
Closes #383.
Probably affects other helpers.
> don't click when disabled

- API.md
- addon-test-support/@ember/test-helpers/dom/double-click.js
- addon-test-support/@ember/test-helpers/index.js
- documentation.yml
- tests/unit/dom/double-click-test.js
This PR adds a `doubleClick` helper to simulate double-clicks, similar to the `click` helper. I'm not sure that it was necessary but I duplicated all the `click` tests.
Here's a little JSBin I threw together to make sure I got the event ordering correct: http://jsbin.com/pulapatapo/1/edit?html,console,output
The order for a focusable element is
```
mousedown
focus
focusin
mouseup
click
mousedown
mouseup
click
dblclick
```
which essentially amounts to two simulated clicks followed by a `dblclick` event.
> Add doubleClick helper

- addon-test-support/@ember/test-helpers/dom/wait-for.js
- tests/unit/dom/wait-for-test.js
Reduces ambiguity if a timeout occurs in a test with multiple waitFor()s
> Include selector in waitFor()'s default timeout message

- addon-test-support/ember-test-helpers/legacy-0-6-x/test-module-for-component.js
This type of link works fine for guides at this point.  We might also want to use the Ember version of the app in question, thoughts?
> Replace hard-coded guides link with /current

- addon-test-support/@ember/test-helpers/dom/fire-event.js
Closes #266 by using the `MouseEvent` constructor in `buildMouseEvent` if it is present. Otherwise, it falls back to the existing `initMouseEvent` function for compatibility with IE 9/10
> Update buildMouseEvent to use MouseEvent constructor if it is present

- addon-test-support/@ember/test-helpers/dom/get-root-element.js
- tests/unit/dom/get-root-element-test.js
Fixes #403 
I used the same element detection logic that -get-element.js uses.
> Fix getRootElement failing when Application.rootElement is an element

- addon-test-support/@ember/test-helpers/settled.js
Not sure if this will fix it, since it seems the list doesn't even get created in the generated content.
> docs(api): try fixing getSettledState list

- API.md
- addon-test-support/@ember/test-helpers/dom/trigger-event.js
Uploading files with an event is a specific code path and the task can
be tough to figure out without an example.
I couldn't think of a better way to document this, but it seemed necessary to me.  I've been using a construct like:
```
inputElement.triggerHandler({
type: 'change',
target: {
files: {
0: file,
length: 1,
item() { return file; }
}
}
});
```
So when converting from jQuery helpers to this addon it was difficult to see how to make file uploads work. Turns out some really nice work is done in `fire-event.js` - just needed to be documented.
> Add some specific documentation for uploading files

- addon-test-support/@ember/test-helpers/dom/type-in.js
- addon-test-support/@ember/test-helpers/index.js
- documentation.yml
- tests/unit/dom/type-in-test.js
The current implementation of `fillIn` does not trigger keydown, keypress and keyup events.
I've recently been working on some stuff that uses these events.  One example being a formatted text input for bank account numbers that only allow certain characters.
I'm not sure if other folks would find this helpful so submitting as a PR for consideration / discussion.
> Add `typeIn` helper to trigger keyup, keypress and keyup events when filling inputs

- .travis.yml
- package.json
- yarn.lock
Unblocks several dependency updates. This is a breaking change and requires a major version bump! (or a minor bump in this case as we're still pre-1.0)
> Drop support for Node.js 4 and below

- addon-test-support/@ember/test-helpers/dom/fire-event.js
- tests/unit/dom/click-test.js
This PR adds `window` as default `view` on generated mouse events.
This fixes #426
> Ensure view is set by default on generated mouse events

- API.md
- addon-test-support/@ember/test-helpers/dom/fire-event.js
- addon-test-support/@ember/test-helpers/dom/trigger-event.js
- tests/unit/dom/select-files-test.js
Following on from the feedback in this PR: https://github.com/emberjs/ember-test-helpers/pull/399
I've updated `triggerEvent` method to accept an `options` param as an object containing a key `files` and issue a deprecation warning when passed an array
---
Closes #399
> Standardize params for calling triggerEvent on file input

- tests/helpers/resolver.js
- tests/integration/settled-test.js
- tests/integration/setup-rendering-context-test.js
- tests/unit/dom/blur-test.js
- tests/unit/dom/click-test.js
- tests/unit/dom/double-click-test.js
- tests/unit/dom/fill-in-test.js
- tests/unit/dom/find-all-test.js
- tests/unit/dom/find-test.js
- tests/unit/dom/focus-test.js
- tests/unit/dom/get-root-element-test.js
- tests/unit/dom/select-files-test.js
- tests/unit/dom/tap-test.js
- tests/unit/dom/trigger-event-test.js
- tests/unit/dom/trigger-key-event-test.js
- tests/unit/dom/type-in-test.js
- tests/unit/dom/wait-for-test.js
- tests/unit/settled-test.js
- tests/unit/setup-application-context-test.js
- tests/unit/setup-context-test.js
- tests/unit/setup-rendering-context-test.js
- tests/unit/teardown-context-test.js
- tests/unit/teardown-rendering-context-test.js
... at least for those tests that use the new APIs
>  tests: Adjust import paths to use `@ember/test-helpers` 

- .travis.yml
- addon-test-support/@ember/test-helpers/-utils.ts
- addon-test-support/@ember/test-helpers/wait-until.ts
- tests/integration/settled-test.js
As of Ember 3.2, `isSettled()` is no longer `true`, even immediately
after `await settled()`. This is because `waitUntil` uses an RSVP
Promise which resolves with a runloop. So when `waitUntil`'s promise
is about to resolve, things _are_ settled, but as soon as we actually
resolve, a new runloop is created which causes `isSettled()` to be
`false`.
> Adds a basic failing test for `settled`

- addon-test-support/@ember/test-helpers/-utils.ts
- addon-test-support/@ember/test-helpers/application.ts
- addon-test-support/@ember/test-helpers/dom/-target.ts
- addon-test-support/@ember/test-helpers/dom/blur.ts
- addon-test-support/@ember/test-helpers/dom/click.ts
- addon-test-support/@ember/test-helpers/dom/double-click.ts
- addon-test-support/@ember/test-helpers/dom/fill-in.ts
- addon-test-support/@ember/test-helpers/dom/find-all.ts
- addon-test-support/@ember/test-helpers/dom/find.ts
- addon-test-support/@ember/test-helpers/dom/focus.ts
- addon-test-support/@ember/test-helpers/dom/get-root-element.ts
- addon-test-support/@ember/test-helpers/dom/tap.ts
- addon-test-support/@ember/test-helpers/dom/trigger-event.ts
- addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
- addon-test-support/@ember/test-helpers/dom/type-in.ts
- addon-test-support/@ember/test-helpers/dom/wait-for.ts
- addon-test-support/@ember/test-helpers/resolver.ts
- addon-test-support/@ember/test-helpers/settled.ts
- addon-test-support/@ember/test-helpers/setup-application-context.ts
- addon-test-support/@ember/test-helpers/setup-context.ts
- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- addon-test-support/@ember/test-helpers/teardown-application-context.ts
- addon-test-support/@ember/test-helpers/teardown-context.ts
- addon-test-support/@ember/test-helpers/teardown-rendering-context.ts
- addon-test-support/@ember/test-helpers/wait-until.ts
This PR imports the type definitions from the `@types/ember__test-helpers` npm package, and applies them to our own TypeScript files.
Further cleanup of those types will happen in follow-up PRs.
> Import type definitions from `@types/ember__test-helpers`

- .npmignore
We fully intend to publish official types support, however we need a better plan on _how_ to do things. Some specific issues are:
* How do we ensure we don't break the types accidentally?
* Since `typescript` itself does not maintain compatibility across versions, how do we ensure the `.d.ts` files that we publish will not become incompatible?
* Do we need an RFC to add this as new public API?
> Add *.ts to `.npmignore`.

- addon-test-support/@ember/test-helpers/-tuple.ts
- addon-test-support/@ember/test-helpers/-utils.ts
- addon-test-support/@ember/test-helpers/application.ts
- addon-test-support/@ember/test-helpers/build-owner.ts
- addon-test-support/@ember/test-helpers/dom/-get-element.ts
- addon-test-support/@ember/test-helpers/dom/-get-elements.ts
- addon-test-support/@ember/test-helpers/dom/-is-focusable.ts
- addon-test-support/@ember/test-helpers/dom/-is-form-control.ts
- addon-test-support/@ember/test-helpers/dom/-target.ts
- addon-test-support/@ember/test-helpers/dom/-to-array.ts
- addon-test-support/@ember/test-helpers/dom/blur.ts
- addon-test-support/@ember/test-helpers/dom/click.ts
- addon-test-support/@ember/test-helpers/dom/double-click.ts
- addon-test-support/@ember/test-helpers/dom/fire-event.ts
- addon-test-support/@ember/test-helpers/dom/focus.ts
- addon-test-support/@ember/test-helpers/dom/get-root-element.ts
- addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
- addon-test-support/@ember/test-helpers/dom/type-in.ts
- addon-test-support/@ember/test-helpers/dom/wait-for.ts
- addon-test-support/@ember/test-helpers/has-ember-version.ts
- addon-test-support/@ember/test-helpers/resolver.ts
- addon-test-support/@ember/test-helpers/settled.ts
- addon-test-support/@ember/test-helpers/setup-application-context.ts
- addon-test-support/@ember/test-helpers/setup-context.ts
- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- addon-test-support/@ember/test-helpers/teardown-context.ts
- addon-test-support/@ember/test-helpers/teardown-rendering-context.ts
- addon-test-support/@ember/test-helpers/wait-until.ts
- tsconfig.json
- types/ember-test-helpers/legacy-0-6-x/build-registry.d.ts
/cc @mike-north @chriskrycho @dfreeman @jamescdavis
> Improve type declarations

- .eslintrc.js
- .gitignore
- .prettierrc.js
* Extract prettier config to stand alone `.prettierrc.js` file (allows other tooling to leverage the same config).
* Add `.eslintcache` to `.gitignore` (we started caching in `yarn lint` but forgot to add this to `.gitignore`)
> Extract Prettier configuration to .prettierrc.js file.

- config/ember-try.js
- package.json
- yarn.lock
See #468 
This PR allows ember-cli-htmlbars-inline-precompile 2.x as well as 1.x, to continue supporting Ember <= 2.12.
> Allow ember-cli-htmlbars-inline-precompile 2.x and 1.x

- addon-test-support/ember-test-helpers/legacy-0-6-x/ext/rsvp.js
As of Ember 1.7 and higher, this customization is done automatically.  Originally we intended to just leave this alone, and not update (since these are already legacy testing systems) but apparently this is actively breaking other fixes in the newer system if *any* older style tests still exist in the test suite.
The main issue with this code on newer Ember versions is that it does not properly call `adapter.asyncStart()` and `adapter.asyncEnd()` which means that we no longer wait for the promise resolution in the test harness itself. :sob:
> Only customize RSVP's async for Ember < 1.7.

- addon-test-support/@ember/test-helpers/teardown-application-context.ts
- addon-test-support/@ember/test-helpers/teardown-context.ts
- addon-test-support/@ember/test-helpers/teardown-rendering-context.ts
- tests/helpers/manual-test-waiter.js
- tests/unit/teardown-context-test.js
- tests/unit/teardown-rendering-context-test.js
In order to allow things like `ember-qunit`'s upcoming async leak detection, we need to avoid waiting for `settled()`. By default we should continue to effectively `await settled()` but when ember-qunit (and soon ember-mocha) is configured to use async leak detection they can appropriately pass `waitForSettled` when they call `teardownContext` / `teardownRenderingContext` / `teardownApplicationContext`.
> Add ability to opt-out of automatic settledness waiting in teardown.

- package.json
- yarn.lock
We previously allowed 1.x and 2.x because 2.x dropped support for Ember < 2.12. That change was revertted in ember-cli-htmlbars-inline-precompile@2.1.0.
> Update dependency on ember-cli-htmlbars-inline-precompile to ^2.1.0.

- addon-test-support/@ember/test-helpers/dom/type-in.ts
- tests/unit/dom/type-in-test.js
Currently, the `typeIn()` helper will only set the `charCode` option of the `KeyboardEvent`. This PR also adds the correct `key` option.
> Ensure typeIn has correct key option

- addon-test-support/@ember/test-helpers/dom/find-all.ts
The `findAll` helper states that it is equivalent to running `querySelectorAll` but that is a lie. Tests were failing when I was doing `querySelectorAll` to `findAll` conversions as I was relying on the `item` method on `NodeList` instances.
> Fix lying doc block on findAll test helper

- addon-test-support/@ember/test-helpers/index.ts
- addon-test-support/@ember/test-helpers/setup-context.ts
- tests/unit/setup-ember-onerror-test.js
It's fairly common to want to temporarily set an `Ember.onerror` handler to test specific aspects of error handling within your application. Newer versions of sinon do not make this easy, as the `Ember.onerror` object is a defined property, and sinon has a codepath that excludes stubbing this particular method (it's a bit weird to _stub_ it anyway, isn't it?). 
This PR introduces a utility to setup `Ember.onerror`, and ensures that it's reset to its original state when the test context is torn down.
TODO:
> Feature - adds setupOnerror function to allow patching Ember.onerror in tests

- addon-test-support/@ember/test-helpers/settled.ts
- addon-test-support/@ember/test-helpers/setup-application-context.ts
- addon-test-support/@ember/test-helpers/setup-context.ts
- addon-test-support/@ember/test-helpers/teardown-application-context.ts
- tests/unit/settled-test.js
- tests/unit/setup-application-context-test.js
This aims to resolve an issue where `settled()` isn't waiting for router transitions. See here: [#411](https://github.com/emberjs/ember-test-helpers/issues/411).
This is a combined effort from myself and @dexturr.
> Wait for pending route transitions as part of settledness check

- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- tests/unit/setup-rendering-context-test.js
> Add deprecation for this.$ in rendering tests

- addon-test-support/@ember/test-helpers/settled.ts
- addon-test-support/ember-test-helpers/legacy-0-6-x/test-module-for-component.js
- tests/dummy/config/optional-features.json
- tests/helpers/ajax.js
`import jQuery from 'jquery'` may trigger a deprecation warning on newer Ember versions, this avoids importing it in favor of using `self.jQuery` directly.
Fixes https://github.com/emberjs/ember-test-helpers/issues/545.
> Avoid importing jQuery, depend on self.jQuery instead.

- addon-test-support/@ember/test-helpers/dom/click.ts
- tests/unit/dom/click-test.js
Fix #551
I copied verifying the key event receiving the modifier by shamelessly stealing from the `checkKey` helper [here](https://github.com/emberjs/ember-test-helpers/blob/master/tests/unit/dom/trigger-key-event-test.js#L163-L170)
> Test and document specifying options to click

- addon-test-support/@ember/test-helpers/-internal/debug-info.ts
- addon-test-support/@ember/test-helpers/index.ts
- addon-test-support/@ember/test-helpers/settled.ts
- addon-test-support/@ember/test-helpers/setup-context.ts
- addon-test-support/ember-test-helpers/legacy-0-6-x/abstract-test-module.js
- tests/test-helper.js
- tests/unit/settled-test.js
- tests/unit/test-debug-info-test.js
- tests/unit/utils/mock-stable-error.js
- tests/unit/utils/test-isolation-helpers.js
- types/@ember/runloop.d.ts
Moving test isolation validation primatives into @ember/test-helpers to enable similar logic to be shared by ember-qunit and ember-mocha.
Currently, the features exists in its entirety in [ember-qunit](https://github.com/emberjs/ember-qunit/blob/master/addon-test-support/ember-qunit/test-isolation-validation.js). In order to share this functionality we need to merge the primitives there into this library.
> Moving test isolation validation primatives into @ember/test-helpers

- API.md
- addon-test-support/@ember/test-helpers/dom/blur.ts
- addon-test-support/@ember/test-helpers/dom/click.ts
- addon-test-support/@ember/test-helpers/dom/double-click.ts
- addon-test-support/@ember/test-helpers/dom/fill-in.ts
- addon-test-support/@ember/test-helpers/dom/focus.ts
- addon-test-support/@ember/test-helpers/dom/tap.ts
- addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
- addon-test-support/@ember/test-helpers/dom/type-in.ts
- documentation.yml
1. Adding examples for dom interaction hepers.
2. Moving setupOnerror and resetOnerror to Test Framework APIs.
3. Created a new name, Debug Helpers, for getDebugInfo to be rendered in the API.md
Decided to do 2 and 3 because I was updating the `API.md` anyways.
Address some of #378 
Address some of #542
> Adding examples for dom interaction hepers.

- addon-test-support/ember-test-helpers/wait.js
this is trying to reexport something that doesn't actually exist
https://github.com/embroider-build/embroider/issues/31#issuecomment-466427253
> Removes bad reexports

- API.md
- addon-test-support/@ember/test-helpers/-internal/debug-info-helpers.ts
- addon-test-support/@ember/test-helpers/-internal/debug-info.ts
- addon-test-support/@ember/test-helpers/index.ts
- documentation.yml
- tests/unit/test-debug-info-test.js
This PR is a WIP of an API allowing applications and addons to add their own custom test debug info. Providing this API can allow for tailored information that can assist in debugging test issues.
> Adding custom test debug info API

- addon-test-support/@ember/test-helpers/-internal/debug-info.ts
- addon-test-support/@ember/test-helpers/settled.ts
- addon-test-support/ember-test-helpers/wait.js
- package.json
- tests/unit/settled-test.js
- tests/unit/test-debug-info-test.js
- tests/unit/utils/test-isolation-helpers.js
- yarn.lock
This PR integrates the new [`ember-test-waiters`](https://github.com/rwjblue/ember-test-waiters) addon into the settled system. It utilizes the new system side-by-side with the legacy test waiters system. Specifically, the new test waiter system gives us
1. The ability to create named waiters
2. The ability to add debug information for when a waiter begins async tracking
3. Primitives that adopters can use to build their own more complicated waiters (though we expect 99% of users will just use the defaults)
This PR:
> Add `ember-test-waiters` and integrate into settledness checks

- addon-test-support/@ember/test-helpers/-internal/debug-info.ts
- addon-test-support/@ember/test-helpers/settled.ts
- tests/unit/settled-test.js
- tests/unit/test-debug-info-test.js
The signature of the `DebugInfo` constructor used to take a series of booleans. This type of signature becomes very hard to use and read, as a succession of `true`/`false` parameters doesn't help the reader understand what's required.
This PR addresses this by converting the signature to take a POJO, in this case of type `SettledState`.
> refactor(DebugInfo): Changes DebugInfo constructor signature to POJO

- API.md
- addon-test-support/@ember/test-helpers/dom/trigger-event.ts
- Fixes missing line break in first `triggerEvent` example, and adds the `files` key to the `options` object.
- Includes additional example for working with the `drop` event.
> Update 'triggerEvent' examples

- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- addon-test-support/ember-test-helpers/legacy-0-6-x/test-module-for-component.js
https://github.com/emberjs/ember.js/pull/18096#issuecomment-507259568
This fixes the latest `ember-canary`.
> fix(setupRenderingContext): compatibility with template factory

- addon-test-support/@ember/test-helpers/dom/fire-event.ts
- tests/unit/dom/select-files-test.js
> Ensure that `triggerEvent` can simulate a file input change event with an empty `FileList`

- testem.js
Chrome ~77 will crash with the `--disable-gpu` flag present. This PR removes it.
> task(config): Removes `--disable-gpu` flag

- package.json
- yarn.lock
Reported upstream in https://github.com/socketio/engine.io/issues/589.
> Pin engine.io subdependency to avoid issues on Node 6.

- addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
- addon-test-support/@ember/test-helpers/dom/type-in.ts
- tests/unit/dom/type-in-test.js
The current behavior of the `typeIn` helper waits for settled promises between text inputs/key events. This is not ideal because it prevents the helper from being used for testing things like debounced functions (like in a typeahead component for instance).
[Here is a repro repo demonstrating the issue.](https://github.com/jakebixbyavalara/concurrency-debounce-repro), I originally encountered the behavior using an `ember-concurrency` `timeout` to debounce a task, which worked fine in the app, but began failing in test due to the change to the `triggerKeyEvent` helper.
This PR fixes the issue by making the `triggerKeyEvent` helper optionally wait for settled promises via a boolean. It's a simple fix that may be overlooking something, so please let me know if there would be a more preferred …
> The typeIn helper should not wait for settled promises between inputs

- index.js
See #604 for context.
Wasn't sure what the `_incrementalTsCompiler` flag was doing - it's not referenced anywhere else in the codebase, so I just removed the reference, but I can add it back if it needs to be something like:
```
if (this.isDevelopingAddon() && this.project._incrementalTsCompiler) {
```
> Only require ember-cli-typescript while developing

- addon-test-support/@ember/test-helpers/dom/-logging.ts
- addon-test-support/@ember/test-helpers/dom/blur.ts
- addon-test-support/@ember/test-helpers/dom/click.ts
- addon-test-support/@ember/test-helpers/dom/double-click.ts
- addon-test-support/@ember/test-helpers/dom/fill-in.ts
- addon-test-support/@ember/test-helpers/dom/focus.ts
- addon-test-support/@ember/test-helpers/dom/tap.ts
- addon-test-support/@ember/test-helpers/dom/trigger-event.ts
- addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
- addon-test-support/@ember/test-helpers/dom/type-in.ts
- tests/unit/dom/logging-test.js
Resolves #740 
The implementation is roughly similar to https://github.com/miragejs/ember-cli-mirage/pull/1818. I've imported the `elementToString()` implementation that [qunit-dom](https://github.com/simplabs/qunit-dom/blob/v0.9.2/lib/helpers/element-to-string.ts) is using to describe target elements if they are not passed in as selector strings.
> Implement test helper logging

- addon-test-support/@ember/test-helpers/dom/type-in.ts
the example was missing the selector string
replaces https://github.com/emberjs/ember-test-helpers/pull/742
> fix `typeIn` documentation example

- API.md
- addon-test-support/@ember/test-helpers/dom/wait-for.ts
- addon-test-support/@ember/test-helpers/wait-until.ts
I personally need this reminder. I keep forgetting to await and return things.
> Add examples to `waitUntil` and `waitFor`

- .travis.yml
- config/ember-try.js
... to ensure that our code works correctly on these LTS releases
> CI: Add test scenarios for Ember 3.8, 3.12 and 3.16

- package.json
- yarn.lock
These were done to fix issues with dependencies dropping support for Node.js 8 with a major version bump. We only support Node.js 10+ now, so these should no longer be necessary.
> Remove obsolete yarn `resolutions`

- addon-test-support/@ember/test-helpers/dom/scroll-to.ts
- addon-test-support/@ember/test-helpers/index.ts
- tests/integration/dom/scroll-to-test.js
Inspired by the `scrollTo` helper from `ember-native-dom-helpers`.
If people are receptive to this, I'll add some tests :)
> Add `scrollTo` helper

- addon-test-support/@ember/test-helpers/dom/-is-focusable.ts
- addon-test-support/@ember/test-helpers/dom/-target.ts
- addon-test-support/@ember/test-helpers/dom/fill-in.ts
- addon-test-support/@ember/test-helpers/dom/type-in.ts
- tests/unit/dom/fill-in-test.js
- tests/unit/dom/type-in-test.js
fixes: https://github.com/emberjs/ember-test-helpers/issues/680
continues: https://github.com/emberjs/ember-test-helpers/pull/681
With this PR `fillIn` and `typeIn` helpers start to fail on attempt to interact with `disabled` form controls.
There is a follow up PR, doing a similar thing for readonly(#779). Extracted it to make review easier.
---
my original intention was also to cover `click` and `doubleclick` and the rest of interaction helpers with the same logic, but seems they intentionally just skip focus for non-focusable elements:
https://github.com/emberjs/ember-test-helpers/blob/f053fe0f6ac1242cb07303a4c69600e223ed5840/addon-test-support/%40ember/test-helpers/dom/click.ts#L18-L20
Assuming changing of this behavior, might be considered a breaking change, I've extracted this part …
> Respect "disabled" in "fillIn" and "typeIn"

- addon-test-support/@ember/test-helpers/dom/-is-focusable.ts
- addon-test-support/@ember/test-helpers/dom/-target.ts
- addon-test-support/@ember/test-helpers/dom/fill-in.ts
- addon-test-support/@ember/test-helpers/dom/type-in.ts
- tests/unit/dom/fill-in-test.js
- tests/unit/dom/type-in-test.js
fixes: #680
based on https://github.com/emberjs/ember-test-helpers/pull/741
> Respect "readonly" in "fillIn" and "typeIn"

- addon-test-support/@ember/test-helpers/dom/blur.ts
- addon-test-support/@ember/test-helpers/dom/click.ts
- addon-test-support/@ember/test-helpers/dom/double-click.ts
- addon-test-support/@ember/test-helpers/dom/focus.ts
- addon-test-support/@ember/test-helpers/dom/tap.ts
- addon-test-support/@ember/test-helpers/dom/trigger-event.ts
- addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
- tests/unit/dom/click-test.js
- tests/unit/dom/double-click-test.js
- tests/unit/dom/focus-test.js
- tests/unit/dom/tap-test.js
- tests/unit/dom/trigger-event-test.js
- tests/unit/dom/trigger-key-event-test.js
With this, any action helper(`click`, `triggerEvent`,...) would fail on attempt to be invoked against `input`, `textarea`, `select` in `disabled` state.
I've extracted it from https://github.com/emberjs/ember-test-helpers/pull/741, cause `fillIn` and `typeIn` seem to be a bit different cases, and it should be easier to review this way. Also this is [possibly](https://github.com/emberjs/ember-test-helpers/pull/741#issuecomment-596437597) a breaking change, so we may want to postpone merging it, while `fillIn` and `typeIn` seem to be more critical to fix.
> [breaking] disable interacting with disabled form controls

- package.json
- yarn.lock
Now that we have dropped support for Ember < 3.8, we no longer need the assign polyfill.
> Remove ember-assign-polyfill dependency.

- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- index.js
- package.json
- tests/integration/dom/scroll-to-test.js
- tests/integration/module-for-acceptance-interop-test.js
- tests/integration/settled-test.js
- tests/integration/setup-rendering-context-test.js
- tests/unit/dom/logging-test.js
- tests/unit/legacy-0-6-x/test-module-for-acceptance-test.js
- tests/unit/legacy-0-6-x/test-module-for-component-test.js
- tests/unit/setup-application-context-test.js
- tests/unit/setup-rendering-context-test.js
- yarn.lock
Now that we have upgrade to ember-cli-htmlbars@4 we can use it directly for inline precompilation.
> Remove ember-cli-htmlbars-inline-precompile.

- addon-test-support/@ember/test-helpers/dom/click.ts
- addon-test-support/@ember/test-helpers/dom/double-click.ts
- tests/unit/dom/click-test.js
- tests/unit/dom/double-click-test.js
Prior to this change, neither click nor double-click helpers were passing the `button` and `buttons` mouseEvent options necessary to emit a left click. I recently ran into an issue as a library I'm using was specifically looking for 'left' clicks and it dawned on me that this should likely be the default behavior for these helpers.
Question for public / repo owners: It's possible, albeit rather unlikely, that this is a breaking change for some people. I'm open to feedback regarding the best way to handle this change so that it does not negatively impact users of this addon.
> Default `click` and `doubleClick` to be left button clicks.

- .eslintrc.js
- .github/workflows/ci-build.yml
- config/ember-try.js
- package.json
- tests/dummy/config/optional-features.json
- tests/unit/setup-rendering-context-test.js
* Use async/await for config/ember-try.js
* Add ember-classic try scenario
* Remove ember-without-application-wrapper scenario (tested in
ember-classic scenario now)
* Fix bug in `ember-lts-3.12` and `ember-lts-3.16` scenario (they wer testing 3.4 :sob: )
* Enable `octane` by default
* Enable template only glimmer components
Closes #316
> Refactor ember-try scenarios.

- package.json
- yarn.lock
This is only needed to support Ember < 2.4.
> Remove ember-debug-handlers-polyfill.

- addon-test-support/@ember/test-helpers/dom/-target.ts
- addon-test-support/@ember/test-helpers/dom/type-in.ts
- tests/unit/dom/type-in-test.js
> Allow type in for contenteditable

- addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
https://github.com/emberjs/ember-test-helpers/issues/871
In order to use triggerKeyEvent in IE11 `Array.find` was replaced by `Array.filter`
_`filter` is a bit slower than `find` here, if it's an issue I'll come up with another solution_
> Issue 871 - Make triggerKeyEvent compatible with the IE11 

- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- tests/unit/setup-rendering-context-test.js
#794 Fixing issue to add deprecation warning to this.clearRender and this.render.
Clone of # #870 but with cleaned up hit history. Wasn't sure how best to fix my forked master.
> Add deprecation for `this.render` and `this.clearRender`

- addon-test-support/@ember/test-helpers/wait-until.ts
- tests/test-helper.js
- tests/unit/dom/double-click-test.js
- tests/unit/dom/fill-in-test.js
- tests/unit/dom/find-test.js
- tests/unit/dom/focus-test.js
- tests/unit/dom/select-files-test.js
- tests/unit/dom/select-test.js
- tests/unit/dom/tap-test.js
- tests/unit/dom/trigger-event-test.js
- tests/unit/dom/trigger-key-event-test.js
- tests/unit/dom/type-in-test.js
- tests/unit/setup-rendering-context-test.js
- tests/unit/wait-until-test.js
There were a few issues this PR is attempting to fix:
1. Correct reset `Application` when it's set to `null`
1. Correctly return from `waitUntil` when we reject so we stop recursing
1. Correctly sets `element` to `null` in tests where element is used.
> fix: Stabilize test suite isolation

- .travis.yml
Many projects dropped support for Node 6, there is no way this will pass. This drops the floating dependencies test run and depends on our lock file + ember-try scenario tests.
> Remove floating dependencies CI run for v1.x branch.

- addon-test-support/@ember/test-helpers/wait-until.ts
- tests/test-helper.js
- tests/unit/dom/double-click-test.js
- tests/unit/dom/fill-in-test.js
- tests/unit/dom/find-test.js
- tests/unit/dom/focus-test.js
- tests/unit/dom/select-files-test.js
- tests/unit/dom/tap-test.js
- tests/unit/dom/trigger-event-test.js
- tests/unit/dom/trigger-key-event-test.js
- tests/unit/dom/type-in-test.js
- tests/unit/setup-rendering-context-test.js
- tests/unit/wait-until-test.js
Brings the changes from https://github.com/emberjs/ember-test-helpers/pull/879 back to v1.x.
> Backport: Ensure `waitUntil` stops recursing when the callback throws an error

- addon-test-support/@ember/test-helpers/setup-context.ts
- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- addon-test-support/@ember/test-helpers/teardown-context.ts
- addon-test-support/@ember/test-helpers/teardown-rendering-context.ts
- tests/test-helper.js
- tests/unit/teardown-rendering-context-test.js
Rely on test framework integration system (e.g. `ember-qunit` or `ember-mocha`) to handle cleanup.
> Remove manual DOM cleanup code after each test.

- ember-cli-build.js
- yarn.lock
We didn't actually have a dependency on `ember-cli-version-checker` so our version was not stable, and a recent update broke it.
I _think_ all we need to do is remove the guarding and whatnot, since more modern versions of the tooling that we rely on already works well.
> Remove usage of ember-cli-version-checker's old `.forEmber` API

- addon-test-support/@ember/test-helpers/setup-context.ts
- addon-test-support/@ember/test-helpers/teardown-context.ts
- package.json
- tests/unit/teardown-context-test.js
- tsconfig.json
- yarn.lock
Moves actual logic from `teardownContext` into `setupContext` by using `registerDestructor` and `associateDestroyableChild`.
> Migrate to using @ember/destroyable for teardown.

- addon-test-support/@ember/test-helpers/dom/focus.ts
- tests/unit/dom/focus-test.js
implements [suggestion](https://github.com/emberjs/ember-test-helpers/issues/692#issuecomment-617563815) by @Turbo87 
I don't feel strongly if we need to cover by tests each helper which uses `__focus__` internally. Please, let me know if we should.
> Blur the previous active element on focus

- addon-test-support/@ember/test-helpers/dom/trigger-event.ts
The `File` constructor takes 2 arguments, first an array with data, second the name.
> fix typo in example that calles `new File(...)`

- addon-test-support/@ember/test-helpers/dom/fire-event.ts
- tests/unit/dom/select-files-test.js
> Ensure setting an empty `value` in FileInput clears the selected files

- addon-test-support/@ember/test-helpers/dom/fire-event.ts
- tests/unit/dom/select-files-test.js
- tests/unit/dom/trigger-event-test.js
Fixes #921 
Not really sure what I did wrong the previous time, now it seems to work fine.
Also moved the testcase to a better location as suggested.
> Make it possible to call `triggerEvent(fileInput, 'change', { files })` twice with the same files

- addon-test-support/@ember/test-helpers/-internal/helper-hooks.ts
For reasons I'm not too sure of, the interoperability between the RSVP promise which is utilized by `nextTickPromise` and the native Promise used at: https://github.com/emberjs/ember-test-helpers/blob/657338372e8344dd2ea50f00d3a72a42ec5c54f3/addon-test-support/%40ember/test-helpers/-internal/helper-hooks.ts#L62 causes numerous component test failures throughout our test suites. Using RSVP's `Promise.all` instead, fixes the test failures.
> Fixes interop issue between native promises and RSVP promises in test helper hooks

- addon-test-support/@ember/test-helpers/dom/-guard-for-maxlength.ts
- tests/unit/dom/fill-in-test.js
- tests/unit/dom/type-in-test.js
Currently, the `maxlength` guard for `typeIn` and `fillIn` helpers doesn't actually execute for `textarea` elements, nor does it discriminate between constrained and non-constrained input types. The issue is actually from an [inverted check](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/dom/-guard-for-maxlength.ts#L16-L17) in the conditional. I've also added more tests to catch this sort of thing. The non-constrained test is slightly contrived, but it would definitely catch a problem if the input type isn't properly verified.
> Fixes maxlength conditional check for textarea & constrained input types

- index.js
Provides information to ember-auto-import so that it can know what the correct target asset should be.
References:
* https://github.com/ef4/ember-auto-import/pull/329
* https://github.com/ember-cli/ember-cli/pull/9411
> Add treeType annotation to hint correct bundle to ember-auto-import

- addon-test-support/@ember/test-helpers/dom/blur.ts
- addon-test-support/@ember/test-helpers/dom/focus.ts
- tests/unit/dom/focus-test.js
This is to address issue #964. The proposed fix is to update the `__blur__` function so that the `event.relatedTarget` property can be set when called from `__focus__`.
As far as I can tell, `element.focus()` automatically triggers `blur` with the correct `event` parameters when the browser is active. This is why it is necessary to wrap the `element.blur();` invocation in an additional check to avoid duplicate triggers of `blur` and `focusout`.
When the browser is not active, we set the `relatedTarget` property for the simulated event (`fireEvent`).
While I did consider calling `fireEvent` directly from https://github.com/drewlee/ember-test-helpers/blob/d0edc5af972cc9fb31c22cd4f48cd9fc0947cac3/addon-test-support/%40ember/test-helpers/dom/focus.ts#L31, I found this undesirable as `blur` …
> Fixes event.relatedTarget for dispatched blur events (#964)

- addon-test-support/@ember/test-helpers/dom/find-all.ts
- addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
- addon-test-support/@ember/test-helpers/dom/wait-for.ts
- addon-test-support/@ember/test-helpers/ie-11-polyfills.ts
- In the first commit we introduce a polyfill for ie11 to support `Array.from` and `Array.prototype.find`.
- In the second commit we optimize `findAll()` and `waitFor` to use `Array.from`
- In the third commit we optimize `triggerKeyEvent` to use `array.find()` instead of `array.filter(predicate)[0]`;
> Polyfilled test selector optimizations 

- addon-test-support/@ember/test-helpers/setup-context.ts
- tests/unit/setup-rendering-context-test.js
The test context already has an owner, in the sense of `this.owner` working. But the standard way to get an owner in Ember is `getOwner`, which doesn't work.
This makes `getOwner` work.
A motivating example are [these tests](https://github.com/embroider-build/embroider/blob/0349de7a5386c30dff8d4aa859fe01138b026878/packages/util/tests/integration/helpers/ensure-safe-component-test.js#L18-L22) which currently use a workaround. They're testing an API that accepts any owned object, and it's nice to use the test context as that object.
> Support getOwner

- package.json
- yarn.lock
Bumping to include: https://github.com/emberjs/ember-test-waiters/pull/231
cc: @rwjblue
> Bumping version of `@ember/test-waiters` to avoid issues in Embroider builds

- .eslintrc.js
- addon-test-support/@ember/test-helpers/-internal/promise-polyfill.d.ts
- addon-test-support/@ember/test-helpers/-internal/promise-polyfill.js
- addon-test-support/@ember/test-helpers/-utils.ts
- package.json
- tests/test-helper.js
- yarn.lock
The UMD wrapping that was used by es6-promise was causing issues in certain contexts (see https://github.com/embroider-build/embroider/issues/677).
This moves from es6-promise to the same promise polyfill that is used by qunit@2.14.0 and higher (promise-polyfill@8.2.0 with some tweaks).
> Inline promise polyfill fallback.

- addon-test-support/@ember/test-helpers/setup-context.ts
- addon-test-support/@ember/test-helpers/setup-onerror.ts
- addon-test-support/@ember/test-helpers/teardown-context.ts
- package.json
- tests/unit/setup-ember-onerror-test.js
- yarn.lock
Resolves an issue where Ember.onerror could get cached too soon.
Fixes #993
> More robust handling in setup-onerror

- addon-test-support/@ember/test-helpers/setup-onerror.ts
- tests/unit/setup-ember-onerror-test.js
* Ignores arguments (these were being passed by QUnit.testDone)
* No-op if missing context or cached value
> Correctly handle resetOnerror

- addon-test-support/@ember/test-helpers/-internal/debug-info.ts
- addon-test-support/@ember/test-helpers/settled.ts
- addon-test-support/@ember/test-helpers/setup-context.ts
- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- package.json
- tests/test-helper.js
- tests/unit/test-debug-info-test.js
- types/@ember/runloop.d.ts
- yarn.lock
- Add `for` and `since` to internal deprecations.
- Use ember-cli-htmlbars@5.7.1
- Fix deprecations introduced by `run.backburner` usage.
- Improve deprecation testing support.
- Fix deprecations for `run.*` method access.
> Fix deprecations with Ember 3.27+

- addon-test-support/@ember/test-helpers/dom/click.ts
- addon-test-support/@ember/test-helpers/dom/double-click.ts
- addon-test-support/@ember/test-helpers/dom/focus.ts
- tests/unit/dom/click-test.js
- tests/unit/dom/double-click-test.js
- tests/unit/dom/tap-test.js
The root cause of the issue is that the blur event is not triggered on
the current active element in the click helper in case if the clicked
element is not focusable.
If the clicked element is focusable the previous active element gets
blur event trough the __focus__ helper.
A call to __blur__ was added for the case when the clicked element
is not focusable.
> Ensure `blur` event fires on prior focused element even if click target is not focusable

- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
This was incorrectly imported from `@ember/application/deprecations`, which seemed to work, but does not work in current canary - I got this error in an addon testing on canary:
```js
Global error: Uncaught Error: Could not find module `@ember/application/deprecations` 
imported from `@ember/test-helpers/setup-rendering-context`
```
Anyway, even if this might/should be fixed in canary, the import is wrong and can be updated to the correct place.
> Correctly import deprecate from `@ember/debug`

- package.json
- tests/integration/setup-rendering-context-test.js
- yarn.lock
This leads to failing tests on Canary, where `{{-in-element}}` is removed.
This updates the test to test the `{{in-element}}` helper on ember versions upwards of 3.20. I did not include an alternate branch to test `{{-in-element}}` on older versions because I figured that is kind of repetitive and we can assume they work the same.
> Test `{{in-element}}` instead of deprecated `{{-in-element}}`

- package.json
- types/ember-data/types/registries/model.d.ts
- yarn.lock
We no longer have `moduleForModel` tests (:tada:), so we don't need ember-data as a dependency any longer. This helps fix a number of issues with our test suite running against canary builds, where the older version of ember-data we were using was missing some required properties of the `deprecate` invocation (but upgrading to newer ember-data wasn't possible because of node engine support).
> Remove ember-data from test harness

- API.md
- addon-test-support/@ember/test-helpers/-internal/deprecations.ts
- addon-test-support/@ember/test-helpers/index.ts
- addon-test-support/@ember/test-helpers/setup-context.ts
- tests/test-helper.js
- tests/unit/setup-context-test.js
Expose deprecation primitives
* `?disableDeprecations` queryParam
* `?debugDeprecations` queryParam
* `import { getDeprecations, getDeprecationsDuringCallback } from ‘@ember/test-helpers’;`
This is a first step in allowing us to deprecate https://github.com/workmanw/ember-qunit-assert-helpers in-favor of these helpers simply being provided by default.
---
Context: This is motivated by 4.0 changes that are incompatible with the original add-on, and the time trade-off of resurrecting that add-on vs adopting its great ideas into mainline. Although users will need to upgrade their `@ember/test-helpers` + `ember-qunit` they will now get the original functionality, + async + bugfixes by default.
I was lead down this path getting embroider working properly on `ember@canary`
---
enables resolving …
> Expose deprecation primitives

- README.md
- addon-test-support/@ember/test-helpers/-internal/build-registry.ts
- addon-test-support/@ember/test-helpers/build-owner.ts
- addon-test-support/@ember/test-helpers/resolver.ts
- addon-test-support/@ember/test-helpers/setup-context.ts
- tests/helpers/resolver.js
Ember.DefaultResolver is no more, so rather trying to use it, we will simply rely on the basic resolver protocol. That way, not concrete object is needed, and we are future proof until such time as that changes.
> Fix ember-canary related issue

- API.md
- addon-test-support/@ember/test-helpers/-internal/deprecations.ts
- addon-test-support/@ember/test-helpers/-internal/is-promise.ts
- addon-test-support/@ember/test-helpers/-internal/warnings.ts
- addon-test-support/@ember/test-helpers/index.ts
- addon-test-support/@ember/test-helpers/setup-context.ts
- tests/unit/-internal/is-promise-test.js
- tests/unit/setup-context-test.js
Expose warning primitives:
* `?disableWarnings` queryParam
* `?debugWarnings` queryParam
* `import { getWarnings, getWarningsDuringCallback } from ‘@ember/test-helpers’;`
This is a second step in allowing us to deprecate https://github.com/workmanw/ember-qunit-assert-helpers in-favor of these helpers simply being provided by default.
---
Context: This is motivated by 4.0 changes that are incompatible with the original add-on, and the time trade-off of resurrecting that add-on vs adopting its great ideas into mainline. Although users will need to upgrade their `@ember/test-helpers` + `ember-qunit` they will now get the original functionality, + async + bugfixes by default.
I was lead down this path getting embroider working properly on `ember@canary`
---
enables resolving …
> Expose warning management primitives

- tests/integration/settled-test.js
- tests/unit/setup-rendering-context-test.js
I’ve left the occurrences where we are explicitly testing the deprecations.
> Remove deprecated this.render + this.clearRenders

- package.json
- server/index.js
- tests/dummy/config/environment.js
- tests/integration/setup-rendering-context-test.js
- yarn.lock
- workaround classic build failure so our tests aren't constantly red. I wasn't able (in the time alloted) track down the issue, but it __apears__ to be a bug/quirk in ember's classic mode. If i had more time I would totally attempt to resolve that, but unfortunately I must stay a little more focused.
- add a quick DX improvement by always redirecting the browser from `/` -> `/tests` when loading the dev harness
> Workaround classic failure

- tests/integration/setup-rendering-context-test.js
After reviewing further with @pzuraq and @krisselden we determined that the issue that was causing the failure with the `{{#in-element` setup is that `insertBefore` is required in order to force "append" mode. Without `insertBefore` the rendering engine will actually **clear** the contents of the target element (which is waht causes the errors we were seeing).
> Bring back `{{#in-element}}` test in ember-classic

- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
ember-canary requires `template` + `environment` be provided to the view. This seems like a reasonable change, but does require “low level” libraries such as `@ember/test-helpers` to make some changes.
(Ember PR https://github.com/emberjs/ember.js/pull/19680)
---
** note: no additional tests required, as ember-canary scenario is broken prior to this changes... in-other words required tests are already part of the test suite  **
> [FIX] This fixes ember-canary

- package.json
Fixes bug in `postpack` that incorrectly deletes `.ts` files rather than `.js`.
> Fixes postpack script to cleanup correct file type

- addon-test-support/@ember/test-helpers/settled.ts
- tests/unit/teardown-context-test.js
The AJAX listener cleanup code wasn't always calling this._super(), so with jQuery integration enabled, lots of application instances were leaking
> Prevent leaking application instances when jQuery integration is enabled

- addon-test-support/@ember/test-helpers/dom/click.ts
- addon-test-support/@ember/test-helpers/dom/double-click.ts
- tests/unit/dom/click-test.js
- tests/unit/dom/double-click-test.js
Preventing default on a mousedown event prevents the focus from changing, so implement that behavior in the click and dblclick DOM helpers
> Preserve focus when default is prevented on mousedown

- .github/workflows/ci-build.yml
- tests/integration/dom/scroll-to-test.js
- tests/integration/settled-test.js
- tests/integration/setup-rendering-context-test.js
- tests/unit/setup-application-context-test.js
- tests/unit/setup-context-test.js
- tests/unit/setup-rendering-context-test.js
Trying to get these tests passing. Fixes for ember-release and beyond
https://github.com/emberjs/ember.js/pull/19728
> Fix CI tests

- addon-test-support/@ember/test-helpers/settled.ts
Fixes #1172 
Related to #1047
Before these changes, the code is confusing a module with one of the functions on that module.
> Fix the way the pending requests module is used in settled.ts

- addon-test-support/@ember/test-helpers/-internal/render-settled.ts
Now that https://github.com/emberjs/ember.js/pull/20053 is merged, we can actually specify the version number for importing `renderSettled` from `@ember/renderer`.
> set ember version for `renderSettled` 

- addon-test-support/@ember/test-helpers/-internal/build-registry.ts
When [`buildOwner`](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/build-owner.ts#L22-L60) is used with a `resolver` instead of an `application`, a custom owner is constructed via [`-internal/build-registry.ts`](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/-internal/build-registry.ts) and used instead of an `ApplicationInstance`.
This custom owner misses the `unregister` patch that was added in https://github.com/emberjs/ember.js/pull/12680 to fix https://github.com/emberjs/ember.js/issues/11173#issuecomment-124897632. It is now on the [`EngineInstance`](https://github.com/emberjs/ember.js/blob/v4.5.0-alpha.5/packages/%40ember/engine/instance.ts#L152-L167).
Fixes …
> Fix usage of `owner.unregister` within `ember-engines` tests

- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- package.json
- yarn.lock
Leverage `ensureSafeComponent` from `@embroider/util` to support rendering a component class via `<this.Foo />` even on Ember < 3.25 (works back a loooong ways).
Fixes https://github.com/emberjs/ember-test-helpers/issues/1220
> Fix issues with `embroider-optimized` scenarios.

- API.md
- documentation.yml
Let's add `tab` to our documentation table of contents and rerun the yarn `docs` script in order to generate out the API docs.
edit; Fixes https://github.com/emberjs/ember-test-helpers/pull/1259
> DOCS: API: publish docs for tab

- addon-test-support/@ember/test-helpers/setup-context.ts
I noticed while migrating some things away from EmberObject (which debounces destroy) that destroy was being triggered more than once due to this. It appears the upstream change has long-since landed and we can remove this and speed up everyone's tests <3
> perf: Remove excessive destroy call

- package.json
It was incorrect previously, causing consumers to see "Cannot find module '@ember/test-helpers' or its corresponding type declarations."
> Fix typesVersions path

- addon-test-support/@ember/test-helpers/index.ts
This brings us one step closer to deprecating ye olde ember-test-helpers package.
> Re-export hasEmberVersion (and its type) from @ember/test-helpers

- addon-test-support/@ember/test-helpers/index.ts
Without this I get lots of warnings when building a project that uses the current @ember/test-helpers master:
```
WARNING in ./node_modules/@ember/test-helpers/index.js 4:0-262
export 'DeprecationFailure' (reexported as 'DeprecationFailure') was not found in './setup-context' (possible exports: ComponentRenderMap, SetUsage, default, getContext, getDeprecations, getDeprecationsDuringCallback, getWarnings, getWarningsDuringCallback, isTestContext, pauseTest, resumeTest, setContext, unsetContext)
@ ./assets/test.js 143:13-65
WARNING in ./node_modules/@ember/test-helpers/index.js 4:0-262
export 'Warning' (reexported as 'Warning') was not found in './setup-context' (possible exports: ComponentRenderMap, SetUsage, default, getContext, getDeprecations, getDeprecationsDuringCallback, getWarnings, …
```
> Use export type for public API

- package.json
Somehow the issue that resulted in us having to use this wonky "public-types/addon-test-support/@ember/test-helpers/*" path was resolved, so the "typesVersions" config is currently broken on master (and 2.9.0).
An issue with post-build cleanup led me astray here, so I fixed that as well.
> Fix types versions

- addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
- tests/unit/dom/trigger-key-event-test.js
Previously, calling `triggerKeyEvent()` with `shiftKey: true` option would trigger an event with an incorrect `key`.
E.g. `triggerKeyEvent(element, 'keydown', 197, { shiftKey: true })` would have a `=` key, instead of `+`.
> Correctly handle special char keyCodes with Shift

- API.md
- addon-test-support/@ember/test-helpers/dom/find-all.ts
- addon-test-support/@ember/test-helpers/dom/find.ts
- addon-test-support/@ember/test-helpers/dom/get-root-element.ts
Let's add an example usage of all of the DOM query helpers (find, findAll, getRootElement) to the API docs. This can close out the checkbox "DOM Query Helpers" in https://github.com/emberjs/ember-test-helpers/issues/378. 
edit; Note, this work is stacked on top of the work for https://github.com/emberjs/ember-test-helpers/pull/1259.
> DOC: API: add DOM query helper examples

- addon-test-support/@ember/test-helpers/dom/-get-element.ts
- addon-test-support/@ember/test-helpers/dom/find-all.ts
- addon-test-support/@ember/test-helpers/dom/find.ts
- addon-test-support/@ember/test-helpers/dom/trigger-event.ts
- addon-test-support/@ember/test-helpers/index.ts
- addon-test-support/@ember/test-helpers/settled.ts
- addon-test-support/@ember/test-helpers/setup-context.ts
- type-tests/api.ts
I compared the `@types/ember__test-helpers` package to the public API of this package to ensure we were:
1. exporting the same things (aside from some of the missing exports I put in other PRs)
2. not losing useful type info (e.g. the `find` overloads)
In the process I noticed a couple of minor issues w/ the types and fixed those as well.
LMK if you'd prefer I broke this up.
> Port some conveniences from @types/ember__test-helpers package

- API.md
- addon-test-support/@ember/test-helpers/setup-application-context.ts
- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
Just lands the work done by @geneukum!
- Closes #1256 
- Closes #1258
> Add docs for routing and render helper examples

- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- tests/unit/setup-rendering-context-test.js
> Remove deprecations targeting v3.0.0

- .github/workflows/ci-build.yml
Should help a bit with reliability (prior versions sometimes failed to
determine the latest version of Volta, and crashed the CI run).
> Update volta-cli/action to v4

- .github/workflows/ci-build.yml
- README.md
- package.json
- tests/dummy/config/ember-try.js
Now that the last Ember LTS of v3 is out of support range, we can drop support here.
> Drop support for Ember 3.x

- .github/workflows/ci-build.yml
- README.md
- Add them to CI.
- Update the README with them.
- Fix an unrelated typo/synax error in the README.
(Note that this already *implicitly* worked, since we've consistently tested against `@next`.)
> Add support for TS 4.8 and 4.9

- addon-test-support/@ember/test-helpers/setup-context.ts
The `TestContext` type has a `[key: string]: unknown` index signature inherited from `BaseContext`. This has led to some confusion, as it muddies the error message folks see when they try to access fields that were present in the DT types but not the native ones, like `element`.
It also doesn't mesh super well with how folks tend to add custom properties to the context type by explicitly declaring them and then setting the `this` type appropriately for their tests. Ultimately we want for that pattern to go away entirely with `<template>`, of course, but in the meantime it would be nice to avoid extra confusion.
The index signature on `BaseContext` doesn't actually appear to be required, and ultimately the way we're using the type is equivalent to just `object`. Accordingly, I'm making …
> Remove the index signature from `TestContext`

- addon-test-support/@ember/test-helpers/setup-context.ts
This error has been around for a very long time, but fixing type type of the `BaseContext` (#1301, #1302) flagged it up as missed in the back-porting work I did last week.
> `TestContext.resumeTest()` returns `void`, not `Promise<void>`

- addon-test-support/@ember/test-helpers/setup-context.ts
- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
This incorporates the same basic fix for `isRenderingTestContext` as the original (#1301) does for `isTestContext`, since that mechanic changes between v2 and v3.
> [backport] Remove the index signature from `TestContext`

- addon-test-support/@ember/test-helpers/-internal/get-component-manager.ts
- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- type-tests/api.ts
The published types from this package rely on `@glimmer/interfaces` in two places:
- in the signature of `render()` to represent that it can accept a component
- in the signature of the internal `getComponentManager` helper
This PR updates the signature of `render()` to simply accept any `object` as its first parameter. This is actually more accurate than the current type—at runtime, `render()` only requires that the object it receives is either a template or is some object with a component manager, but "has a component manager" isn't something we're able to model in the TS type system.
It also updates the return type of the `getComponentManager` utility to `unknown`, as we never actually interact with the manager, we only check for its existence. (In reality this change is likely …
> Avoid unnecessary dependencies on `@glimmer` types

- addon-test-support/@ember/test-helpers/-internal/get-component-manager.ts
- addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- type-tests/api.ts
This is a backport of #1304 for v2
> [backport] Avoid unnecessary dependencies on `@glimmer` types

- addon-test-support/@ember/test-helpers/setup-context.ts
Allow them to proceed to the next handler.
Observed this behavior in an application: Deprecations thrown outside of a running test are swallowed by this handler. For example, when running tests on ember-resolver, no @ember/string deprecations are thrown, even though deprecate is called. 
I am not sure if this was intentional, but it makes it hard to test that a deprecation isn't thrown by a package. 
How can this be tested in the test suite here?
I attempted various ways to test this in the test suite but was unsuccessful. I attempted to add my own registerDeprecationHandler to confirm it was called by the one in `setup-context`, but I was not able to register my handler in advance of the handler in `setup-context`, which means mine was always called before the one in `setup-context`. My …
> Don't swallow deprecations and warnings when there is no test context

- API.md
- addon-test-support/@ember/test-helpers/dom/find-all.ts
- addon-test-support/@ember/test-helpers/dom/find.ts
The findAll example shows up in the section of the API docs for the find helper and vice versa. We should swap these to make the docs as clear as possible.
While we're here, `Commit: cba01bea` updated `setupContext`, renaming its first param from `context` to `base` in the process. It did not regenerate out the docs as part of the changeset, so building the docs results in this change locally.
Let's fixup that commit here so that we can build the docs without creating any local changes.
This closes https://github.com/emberjs/ember-test-helpers/issues/1317.
> [DOC] Swap `find` and `findAll` examples

- package.json
Pre-req for converting to a v2 addon.
~~According to @chriskrycho, we're preparing for a major anyway: https://github.com/emberjs/ember-test-helpers/pull/1249#issuecomment-1354062379~~
Requirement stems from: https://github.com/wessberg/rollup-plugin-ts/issues/202
> Use node 16 for development instead of node 14

- API.md
- addon-test-support/@ember/test-helpers/-internal/deprecations.ts
- addon-test-support/@ember/test-helpers/-internal/warnings.ts
- addon-test-support/@ember/test-helpers/dom/click.ts
- addon-test-support/@ember/test-helpers/setup-application-context.ts
- addon-test-support/@ember/test-helpers/setup-context.ts
- tests/helpers/qunit-test-adapter.js
- tests/unit/dom/blur-test.js
- tests/unit/dom/tab-test.js
- tests/unit/dom/type-in-test.js
- tests/unit/setup-context-test.js
Just fixing a few typos throughout the repo.
The one in `setup-application-context` is user-facing. It showed up in my work project, which inspired me to make this PR 😄
> doc: fix various typos in the repo

- addon/tests/dummy/config/ember-try.js
- addon/tests/helpers/start-app.js
- addon/tests/unit/setup-context-test.js
Per: https://github.com/emberjs/ember.js/issues/20418
Canary tests were hanging,
Locally:
```
Died on test #1: Could not find module `@ember/polyfills` imported from `dummy/tests/unit/setup-context-test`
at TestLoader.moduleLoadFailure (http://localhost:4202/assets/tests.js:1184:22)
at TestLoader.require (http://localhost:4202/assets/test-support.js:6931:14)
at TestLoader.loadModules (http://localhost:4202/assets/test-support.js:6923:14)
```    
-------------
To fix, I had to remove `@ember/polyfills` -- which would be a breaking change -- but that's fine, as we're preparing for v3 anyway
> Get ember-canary passing

- addon/addon-test-support/@ember/test-helpers/-internal/build-registry.ts
The `setupContainer` function of `ember-data` expects an application instance to be passed - in this case that is the faked owner object that we create when using a custom resolver in tests.
This behaviour previously worked because `ember-data` supported the usage of legacy function `optionsForType` which exists on the `registry` object. However, they removed that legacy fallback in v4 and replaced it with `registerOptionsForType` which does not exist on the registry but only on the owner.
Resolves #1386
> Pass owner instead of registry to ember-data's setupContainer

- addon/CHANGELOG.md
- addon/package.json
Some confusing comparisons:
- https://github.com/emberjs/ember-test-helpers/compare/master...v2.9.3
- https://github.com/emberjs/ember-test-helpers/compare/v2-x
I reviewed the code with the following commits, starting with the first one I did not see in my skim of the t`git log` on `master`:
- https://github.com/emberjs/ember-test-helpers/commit/1d22a8e8c6b54bf02e9cf34a2c6867be1c94ea25
- https://github.com/emberjs/ember-test-helpers/commit/a34c29b71d88cb16a876900ce657366916da08ba
- https://github.com/emberjs/ember-test-helpers/commit/e3f1cb845d27e762ffc15983675086beece2c787
- https://github.com/emberjs/ember-test-helpers/commit/421d2a03c9f20ee40e8d6eb1ec19e9febaa5bb8f
- https://github.com/emberjs/ember-test-helpers/commit/20c6cf9a6a8303b683ab28cba9c2c29b6fc7a5d9
- …
> Sync with the v2.x branch

- addon/addon-test-support/@ember/test-helpers/dom/blur.ts
- addon/addon-test-support/@ember/test-helpers/dom/click.ts
- addon/addon-test-support/@ember/test-helpers/dom/double-click.ts
- addon/addon-test-support/@ember/test-helpers/dom/fill-in.ts
- addon/addon-test-support/@ember/test-helpers/dom/fire-event.ts
- addon/addon-test-support/@ember/test-helpers/dom/focus.ts
- addon/addon-test-support/@ember/test-helpers/dom/tap.ts
- addon/addon-test-support/@ember/test-helpers/dom/trigger-event.ts
- addon/addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
- addon/addon-test-support/@ember/test-helpers/dom/type-in.ts
This change is mostly a no-op, but a require change as our recommend v2 addon rollup config does not support "self-imports" (though it can be added with extra config).
However, importing from ./module is much easier and less typing than using the full path.
> Use sibling import for logging so that these files are rollup compatible

- addon/addon-test-support/@ember/test-helpers/setup-rendering-context.ts
- addon/package.json
- yarn.lock
This usage of `ensureSafeComponent` is a no-op on all the versions of ember supported by this addon.
> ensureSafeComponent is not needed on Ember > 3.25

- addon/tests/helpers/resolver.js
This isn't needed, it seems?
we don't support folks doing `setResolver` and all apps use `setApplication`, yeah?
> Remove extraneous event-dispatcher wiring and a amd/require

- addon/addon-test-support/ember-test-helpers/has-ember-version.ts
This is a breaking change, but one required for v2 conversion.
We do not need this utility, as we can use embroider/macros. 
(but also `hasEmberVersion` still exists in `@ember/test-helpers` (for now))
> remove has-ember-version

- addon/.npmignore
- addon/package.json
- addon/types.tsconfig.json
in #1397 a user has reported that types are missing and they are getting an error. 
This PR updates the `.npmignore`  file and the package.json file to more correctly reflect what should be getting published re:types. 
This error seems to be related to the differences between `npm pack` and `yarn pack`.
Also not 100% sure this will be the fix but thanks to @gitKrystan @chriskrycho and @NullVoxPopuli for working through this toward a potential solution.
> fixing the release

- addon/addon-test-support/@ember/test-helpers/-internal/get-component-manager.ts
- addon/addon-test-support/@ember/test-helpers/-internal/is-component.ts
- addon/addon-test-support/@ember/test-helpers/setup-rendering-context.ts
AFAICT [this change](https://github.com/emberjs/ember-test-helpers/pull/1382/files#diff-d3135c2567a56aba0c3f1dd551a3eca6e8c8287a802a584c2b127d8a032ad51a) from #1382 is incorrect but coincidentally works because `owner` is truthy.
It appears that `getInternalComponentManager`'s signature is `(definition: object, isOptional?: true | undefined) => InternalComponentManager | null` and has been for a while:
https://github.com/glimmerjs/glimmer-vm/blob/14413355ef6b48c1ab416a91fb7ff950cf8511d8/packages/%40glimmer/manager/lib/internal/index.ts#L177-L211
This issue was exposed by https://github.com/emberjs/ember-test-helpers/pull/1389
> Fix `isComponent` types

- .github/workflows/ci-build.yml
- addon/package.json
- addon/tests/dummy/config/ember-try.js
Note that there are still issues with types support for Ember 5.1, which will #1389 will address.
> Add Ember 5.0 to support matrix (Fixes #1403)

- .gitignore
- addon/.gitignore
To get CI green, this needs to be merged: https://github.com/emberjs/ember-test-helpers/pull/1406
Resolves https://github.com/emberjs/ember-test-helpers/issues/1402#
Previously, both `npm pack` and `yarn pack` would not include the js files.
This change makes it so that the js files are included in the tarball.
It's possible this is fallout from v2 conversion part 1, where the repo was split in to a monorepo, as the .gitignore was left in the monorepo root, and not. 
(I expected v2 conversion of all 3 test projects to be < 1 month, so... my expectations are probably to blame here.....)
<details><summary>The contents of `npm pack`'s tarball:</summary>
```
"
package/README.md
package/addon-test-support/@ember/test-helpers/-internal/build-registry.js …
```
> Fix npm pack to include js files

- addon/package.json
- addon/tests/dummy/config/ember-try.js
- yarn.lock
the `@embroider/*` packages are no longer released in lockstep, so each version must individually be fetched
> fix embroider tests

- addon/addon-test-support/@ember/test-helpers/setup-context.ts
- addon/tests/unit/setup-context-test.js
This implicitly worked for as long as `this.setProperties` existed, because it ultimately forwards to Ember's `setProperties`, which also implicitly works with this. Although this is not public API, and indeed is not desirable, changing it (implicitly and accidentally!) will break many consumers who are relying on it (most likely to end up happening transitively, e.g. via local/custom test helpers).
> bugfix: handle `null` and `undefined` in `setProperties`

- .github/workflows/push-dist.yml
If merged, this PR adds https://github.com/kategengler/put-built-npm-package-contents-on-branch/ which should provide a little extra confidence for folks doing new releases (especially as we add new maintainers and update packages to use the v2/embroider guidance). 
Still need to confirm some of the config settings but after that I will mark it ready for review.
> adds new workflow file to provide release branches

- addon-test-support/@ember/test-helpers/setup-context.ts
- tests/unit/setup-context-test.js
Backport #1417 to v2.x:
> This implicitly worked for as long as `this.setProperties` existed, because it ultimately forwards to Ember's `setProperties`, which also implicitly works with this. Although this is not public API, and indeed is not desirable, changing it (implicitly and accidentally!) will break many consumers who are relying on it (most likely to end up happening transitively, e.g. via local/custom test helpers).
> (backport) bugfix: handle `null` and `undefined` in `setProperties`

- .github/workflows/ci-build.yml
- addon/package.json
- addon/tests/dummy/config/ember-try.js
With this change, CI for this package will detect issues caused by "breaking" differences between `@types` packages, ember preview types, and ember stable types.
> Check types in test matrix

- addon/addon-test-support/@ember/test-helpers/setup-rendering-context.ts
The canary build started failing after https://github.com/emberjs/ember.js/pull/20570 was merged. We were never supposed to pass a `TemplateFactory` to `OutletState`, but it was previously tolerated. The pattern was fixed in the pass, but regressed when implementing support for `render(<template>...</template>)`.
No new tests because existing ones are already failing. If we wait till https://github.com/emberjs/ember.js/pull/20577 lands then we should see it turn into a deprecation, and this fix will remove the deprecation.
> Fix ember-canary error/deprecation

- addon/tests/unit/setup-application-context-test.js
Extracted from: https://github.com/emberjs/ember-test-helpers/pull/1450
Example of the failure in CI on main: https://github.com/emberjs/ember-test-helpers/actions/runs/10014604943/job/27684657206#step:5:582
> Fix: You attempted to render a path ({{model.post_id}}), but model was not in scope:

- addon/addon-test-support/@ember/test-helpers/dom/-guard-for-maxlength.ts
Fixes #1459 
Issue: `maxLength` attribute is being read instead of the correct `maxlength` attribute.
> Use the right attribute - `maxlength` instead of `maxLength`

- CONTRIBUTING.md
Fixes #1461 
Fix the git clone url in `CONTRIBUTING.md` file
> correct git clone url for the repo

- .github/workflows/ci-build.yml
- test-app/tests/helpers/browser-detect.js
- test-app/tests/unit/dom/blur-test.js
- test-app/tests/unit/dom/click-test.js
- test-app/tests/unit/dom/double-click-test.js
- test-app/tests/unit/dom/fill-in-test.js
- test-app/tests/unit/dom/focus-test.js
- test-app/tests/unit/dom/tab-test.js
- test-app/tests/unit/dom/tap-test.js
- test-app/tests/unit/dom/type-in-test.js
Unblocks: https://github.com/emberjs/ember-test-helpers/pull/1470
Last successful build (nightly cron): https://github.com/emberjs/ember-test-helpers/actions/runs/10173407362
Next nightly cron failed: https://github.com/emberjs/ember-test-helpers/actions/runs/10191329093
Findings:
- failures only affect chrome (127.0.6533.99, 127.0.6533.100, (etc?))
- Chrome Canary (129.0.6658.0) has the same behavior
- relevant changes https://chromium.googlesource.com/chromium/src/+log/127.0.6533.77..127.0.6533.120?pretty=fuller&n=10000
- potentially related bug reports
- https://issues.chromium.org/issues/346898523 
- but none of them recent: https://issues.chromium.org/issues?q=selectionchange%20created%3E2024-07-30
- Could this be caused by https://chromestatus.com/feature/5255454895898624 ? 
- …
> Get tests passing w/ Chrome's new selectionchange event behavior

- .github/workflows/ci-build.yml
I need to figure out what went wrong in ember-source, so here is step one -- see what tests were failing
Blocked by: https://github.com/emberjs/ember-test-helpers/pull/1473
> Re-enable try scenarios against 5.10, 5.11-beta and 5.12-canary

- addon/addon-test-support/@ember/test-helpers/-internal/build-registry.ts
Extracted from: https://github.com/emberjs/ember-test-helpers/pull/1471
> Remove require usage, dropping support for automatic ember-data/setup-container inclusion

- .github/workflows/ci-build.yml
Extracted from https://github.com/emberjs/ember-test-helpers/pull/1471/commits/6a0c2e4d73cc44d6f262e2c25887e5b6c189c44a
Reason:
- we want to use modern tooling (and specify extensions in imports), and TS < 5 doesn't support specifying ts extensions in import paths.
> Drop support for TS < 5

- addon/src/settled.ts
This was mistakenly exported in https://github.com/emberjs/ember-test-helpers/pull/1486/files#r1744091959
Resolves: https://github.com/emberjs/ember-test-helpers/issues/1502
> Don't export checkWaiters

- addon/src/setup-context.ts
- addon/src/teardown-context.ts
- test-app/tests/unit/dom/fill-in-test.js
- test-app/tests/unit/setup-application-context-test.js
- test-app/tests/unit/setup-context-test.js
- test-app/tests/unit/teardown-context-test.js
In v2.0.0 @ember/test-helpers refactored to use `@ember/destroyable` for teardown which also meant
that the application context was destroyed during teardown, where previously it was only cleaned up
and the application (`context.owner`) was destroyed.
In our application tests we simulate a page refresh by calling `teardownContext` and
`setupContext`. The destroyable change broke this functionality because the context is now marked
as destroyed.
This commit effectively reverts the change to use `@ember/destroyable` and adds tests to ensure that
the context is not destroyed so that it can be reset during a test.
This addresses https://github.com/emberjs/ember-test-helpers/issues/1452 raised by @mixonic 
The @ember/destroyable change was made in #914
> Make test context reusable during a test

- .github/workflows/ci-build.yml
- addon/package.json
- addon/pnpm-lock.yaml
- test-app/config/ember-try.js
- test-app/package.json
- test-app/pnpm-lock.yaml
- test-app/tests/unit/settled-test.js
> v4: Widen test-waiters range

- addon/src/-internal/build-registry.ts
- addon/src/setup-rendering-context.ts
Private APIs I'm not removing, but _are_ tested in ember.js, so we don't accidentally break:
- Owner-related Mixins: https://github.com/emberjs/ember.js/blob/aedf98854d89887f5779a3ee0d4f0ff2a26a8039/packages/ember/tests/reexports_test.js#L344-L345
- Registry: https://github.com/emberjs/ember.js/blob/aedf98854d89887f5779a3ee0d4f0ff2a26a8039/packages/ember/tests/reexports_test.js#L283
- getOnerror / setOnerror: https://github.com/emberjs/ember.js/blob/aedf98854d89887f5779a3ee0d4f0ff2a26a8039/packages/ember/tests/reexports_test.js#L302
Note: 
- we should have a public API way to build an owner so we can have `@ember/test-helpers` not use private APIs.
- would allow us to not use the Mixins
- I can delete more, but it would technically be a breaking change for this library, I think
- we have …
> Cleanup some private API and now-unsupported usage

- addon-test-support/@ember/test-helpers/setup-context.ts
backport of https://github.com/emberjs/ember-test-helpers/pull/1449
> backport globalThis setupContext

- addon/src/setup-application-context.ts
- addon/src/setup-rendering-context.ts
- test-app/tests/unit/setup-rendering-context-test.js
This is a follow-up to https://github.com/emberjs/ember.js/pull/20683
> Remove `application-template-wrapper` feature

- addon/package.json
embroider, auto-import, and ember-cli before them handled virtual deps without a package.json entry.
package.json entries win over virtual deps, so we don't want to declare ember-source or @glimmer/tracking as peers.
Related:
- https://github.com/tracked-tools/tracked-toolbox/pull/211
- https://github.com/emberjs/ember-test-helpers/pull/1543
- https://github.com/NullVoxPopuli/ember-resources/pull/1189
- https://github.com/universal-ember/kolay/pull/187
- https://github.com/universal-ember/reactiveweb/pull/139
- https://github.com/universal-ember/ember-primitives/pull/471
- https://github.com/universal-ember/docs-support/pull/77
> Remove unneeded peers

- addon/src/dom/trigger-event.ts
- test-app/tests/unit/dom/trigger-event-test.js
- type-tests/api.ts
I believe `triggerEvent` is too restrictive if it forbids all events on a form control with the `disabled` attribute. While the specification only mentions "click events" and MDN refers to "browsing events," all browsers currently allow mouse tracking events, such as `mouseenter` and `mouseleave`, to trigger on disabled controls. Additionally, there are events unrelated to user interaction, like `transitionend` and `animationend`.  
Beyond known events, there's also the case of `CustomEvent`, which is entirely valid in browsers but is currently blocked by `triggerEvent`.  
Maintaining a comprehensive list of forbidden or allowed events might not be practical or sustainable. However, I suggest providing testers with an option to trigger events on disabled elements if necessary.
This PR …
> Add `force` argument to `triggerEvent`
