lib/ember-test-helpers/test-module.js

Fix `afterTeardown` callback removal.

---

lib/ember-test-helpers/isolated-container.js

`registry` is not necessarily avaiable in this context.

Use container to register custom DS keys.

---

README.md

Adds syntax highlighting to example code block

Add javascript syntax highlighting to README example

---

lib/ember-test-helpers/test-module.js
tests/test-module-for-component-test.js
tests/test-module-test.js

punctual punctuation

---

lib/ember-test-helpers/test-module-for-component.js
tests/test-module-for-component-test.js

Add support for closure actions in component integration test

---

tests/test-module-for-integration-test.js

I was originally trying to prove that something was broken, but it looks like it's related to ember-cli-mocha, which I'm in the process of writing an issue for. I figured I would still offer these additional tests I wrote to get more coverage.
If these tests are not useful, feel free to close this.

Additional dom testing events.

---

bower.json
config/ember-try.js

* Add Ember 2.0.0.
* Specify Ember Data version for each ember-try scenario.

Update ember-try config.

---

bower.json
config/ember-try.js
ember-cli-build.js
package.json

Test ember-data-2.3 in addon mode.

---

bower.json
package.json

All new package versions are within their currently specified ranges, just updated to the latest release in that range.

Updating Package Versions within current range

---

lib/ember-test-helpers/abstract-test-module.js
lib/ember-test-helpers/test-module-for-integration.js
lib/ember-test-helpers/test-module.js
tests/test-module-test.js

Supports efforts in https://github.com/rwjblue/ember-qunit/pull/237.

Allow test frameworks to set context to use.

---

README.md

Document ability to set module-specific resolver

---

.travis.yml

Travis: Automatically publish tags to npm

---

addon-test-support/@ember/test-helpers/index.js
addon-test-support/@ember/test-helpers/settled.js
tests/helpers/ajax.js
tests/integration/settled-test.js
tests/test-helper.js
tests/unit/application-test.js
tests/unit/legacy-0-6-x/test-module-for-model-test.js
tests/unit/legacy-0-6-x/test-module-test.js
tests/unit/settled-test.js
tests/unit/setup-context-test.js
tests/unit/setup-rendering-context-test.js
yarn.lock

`isSettled()` will return boolean, and `getSettledState()` will return an object with a number of properties that you can use to see _why_ `isSettled()` returns `false`...
Also:
* Add actual unit tests for `settled`.
* Extract `tests/helpers/ajax.js` to ease testing requests.
* Move existing settled tests to clearly be "integration".

Refactor `isSettled` to allow better insight into current state.

---

.travis.yml
package.json
yarn.lock

similar to https://github.com/emberjs/ember-qunit/pull/299

CI: Use Node 4 for tests

---

.travis.yml
README.md
package.json
testem.js
tests/helpers/start-app.js
yarn.lock

Update ember cli

---

.eslintrc.js
.travis.yml
config/ember-try.js
package.json
testem.js
yarn.lock

Migrate to testing against ember-source tarballs.

---

addon-test-support/@ember/test-helpers/dom/-get-element.js
addon-test-support/@ember/test-helpers/dom/-get-elements.js
addon-test-support/@ember/test-helpers/dom/-to-array.js
addon-test-support/@ember/test-helpers/dom/find-all.js
addon-test-support/@ember/test-helpers/dom/find.js
addon-test-support/@ember/test-helpers/dom/wait-for.js
addon-test-support/@ember/test-helpers/index.js
tests/unit/dom/find-all-test.js
tests/unit/dom/find-test.js

Implement `find()` and `findAll()` DOM helpers

---

addon-test-support/@ember/test-helpers/dom/get-root-element.js
addon-test-support/@ember/test-helpers/index.js
tests/unit/dom/get-root-element-test.js

Make getRootElement() public

---

addon-test-support/@ember/test-helpers/dom/fire-event.js
tests/helpers/events.js
tests/unit/dom/click-test.js

This addresses https://github.com/emberjs/ember-test-helpers/issues/330

Check `nodeType` rather than `instanceOf` Check

---

package.json
tests/helpers/events.js
tests/unit/dom/blur-test.js
tests/unit/dom/click-test.js
tests/unit/dom/fill-in-test.js
tests/unit/dom/focus-test.js
tests/unit/dom/tap-test.js
tests/unit/dom/trigger-event-test.js
tests/unit/dom/trigger-key-event-test.js
yarn.lock

This PR updates `qunit` to the latest release and fixes the issue resulting from the changed `verifySteps()` behavior.
Resolves #335, Closes #341
/cc @snewcomer

Update `qunit` to v2.5.1

---

addon-test-support/@ember/test-helpers/-utils.js

Fix RSVP.Promise overriding Promise in native promise detection.

---

.travis.yml

roughly similar to https://github.com/emberjs/data/blob/v3.6.0-beta.1/.travis.yml#L15-L23

CI: Only run for `master`, PRs and version tags and branches

---

.eslintignore
.eslintrc.js
.gitignore
addon-test-support/@ember/test-helpers/-utils.ts
addon-test-support/@ember/test-helpers/setup-rendering-context.ts
package.json

Improve ESLint usage

---

package.json
yarn.lock

```
rm yarn.lock
yarn
git add yarn.lock
```

Refresh `yarn.lock`.

---

addon-test-support/@ember/test-helpers/index.ts

Addresses https://github.com/emberjs/ember-qunit/pull/453#discussion_r259368779

Exporting getDebugInfo as public

---

addon-test-support/@ember/test-helpers/dom/trigger-event.ts

Fix File Upload Example

---

yarn.lock

After pulling the latest from upstream master and running `yarn`, my lock file was dirty. This adds the lock file changes to master.

task(lockfile): Updates master's lock file with latest changes

---

API.md
addon-test-support/@ember/test-helpers/index.ts
addon-test-support/@ember/test-helpers/setup-application-context.ts
addon-test-support/@ember/test-helpers/setup-context.ts
addon-test-support/@ember/test-helpers/setup-rendering-context.ts
addon-test-support/@ember/test-helpers/test-metadata.ts
documentation.yml
tests/unit/setup-application-context-test.js
tests/unit/setup-context-test.js
tests/unit/setup-rendering-context-test.js
tests/unit/test-metadata-test.js

feat(test metadata): Adds test metadata primitives

---

.eslintrc.js
package.json
yarn.lock

This should hopefully unblock #764

Update eslint-typescript packages

---

README.md

We should probably document publicly what versions our releases are supporting.

README: Add "Compatibility" section

---

testem.js

This matches a corresponding change in ember-cli's blueprints.

Increase browser start timeout.

---

RELEASE.md
package.json

* Add `launchEditor` for release-it-lerna-changelog
* Add `tokenRef` (to use the same token for changelog + GH release)

Tweak automated release setup.

---

types/require.d.ts

Fix internal types for `require`'s `has` method

---

tests/index.html

This allows us to rely on the testing harness itself to ensure things are cleaned up if some failure occurs mid-test...

Move `#ember-testing-container` into `#qunit-fixture` element.

---

ember-cli-build.js
index.js

This was missed in e6beae65fb9698abadc83d9508cd7542c326b4a6.

Remove unneeded `treeForVendor`

---

addon-test-support/@ember/test-helpers/-internal/debug-info.ts
addon-test-support/@ember/test-helpers/build-owner.ts
addon-test-support/@ember/test-helpers/settled.ts
addon-test-support/@ember/test-helpers/setup-onerror.ts
tests/helpers/module-for-acceptance.js
tests/helpers/resolver.js
yarn.lock

the lockfile was getting crufty, causing some other PRs to have unexpected prettier changes.
Rather then messing up those PRs, this attempts to keep it isolated.

re-roll the lockfile + re-run prettier

---

package.json
yarn.lock

Reported the Node 10 compatibility issue in https://github.com/release-it/release-it/issues/797

Pin release-it to 14.10.1 due to Node 10 incompatiblities

---

.github/workflows/ci-build.yml
config/ember-try.js
package.json
yarn.lock

- `@emberjs/test-waiters`
- add ember-source 3.24 to ember-try

Upgrade @ember/test-waiters to 3.0.0

---

API.md

Make it clear that render overwrites, not append.
Closes #1018

[docs] Clarify render example

---

tests/unit/setup-application-context-test.js

https://github.com/emberjs/ember.js/runs/4204475089?check_suite_focus=true
I'm working on adding smoke tests for some ember packages in the ember.js repo and noticed it caught a failure!
https://github.com/emberjs/ember.js/pull/19728

[test] bug: Fix latest ember.js errors for LinkTo invocation

---

addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts

To paraphrase the `keyFromKeyCode` comment: This is not a comprehensive list, but it is better than before 😉

Add more keyCode mappings

---

.npmignore

Actually publish .d.ts

---

API.md
addon-test-support/@ember/test-helpers/dom/tab.ts
package.json
type-tests/api.ts

See https://github.com/emberjs/ember-test-helpers/blob/master/API.md#parameters-7
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember__test-helpers/dom/triggerTab.d.ts

Ensure types reflect optional-ness of tab options

---

addon-test-support/@ember/test-helpers/index.ts
type-tests/api.ts

See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember__test-helpers/index.d.ts#L29

Export type for Target

---

.npmrc
pnpm-lock.yaml

Extracted from https://github.com/emberjs/ember-test-helpers/pull/1471
These changes help us be good stewards of the ecosystem.

Use strict .npmrc

---

.github/workflows/ci-build.yml
API.md
addon/package.json
package.json

Required before moving forward with v2 conversion: https://github.com/emberjs/ember-test-helpers/pull/1471
What an error looks like

Add Docs-Generation to CI -- will error if docs get out of sync and provides actionable information towards resolution.

---

.github/workflows/ci-build.yml
addon/package.json
test-app/package.json
test-app/pnpm-lock.yaml

Exploring a hypothesis from https://github.com/emberjs/ember-test-helpers/issues/1481
Resolves https://github.com/emberjs/ember-test-helpers/issues/1481

Resolve Error: @ember/test-helpers is trying to import from @ember/-internals but that is not one of its explicit dependencies

---

addon/package.json

Extracted from: https://github.com/emberjs/ember-test-helpers/pull/1486
Ultimately a long-term fix will come from: https://github.com/embroider-build/embroider/pull/2075
(and work for everyone)
Resolves: https://github.com/emberjs/ember-test-helpers/issues/1481

Add @ember/renderer to externals
